let schools=[];
let loadError='';
const demoSchools=[
{name:'堆龙德庆区第二中学',code:'XZDL0021',level:'初中',state:'normal',status:'正常运营',plan:'成长套餐',dates:'2024-01-01 ~ 2024-12-31',remain:'剩余 219 天',nums:'1,560 / 109 / 38',activity:'5月30日 课程学习',risk:'数据不足',crest:'redc'},
{name:'堆龙德庆区第一小学',code:'XZDL0007',level:'小学',state:'normal',status:'正常运营',plan:'基础套餐',dates:'2024-03-01 ~ 2025-02-28',remain:'剩余 323 天',nums:'1,326 / 88 / 27',activity:'5月29日 测评完成',risk:'无风险',crest:'greenc'},
{name:'乃琼街道中心小学',code:'XZDL0012',level:'小学',state:'expiring',status:'即将到期',plan:'成长套餐',dates:'2023-06-01 ~ 2024-06-15',remain:'剩余 15 天',nums:'986 / 65 / 14',activity:'5月28日 资源上传',risk:'数据不足',crest:'bluec'},
{name:'古荣乡小学',code:'XZDL0017',level:'小学',state:'stopped',status:'停用',plan:'基础套餐',dates:'2022-09-01 ~ 2023-09-01',remain:'已过期 631 天',nums:'382 / 32 / 9',activity:'2023年8月15日 最后登录',risk:'停用中',crest:'redc'},
{name:'羊达乡教学点',code:'XZDL0028',level:'教学点',state:'normal',status:'正常运营',plan:'试用套餐',dates:'2024-05-01 ~ 2024-07-31',remain:'剩余 61 天',nums:'156 / 12 / 3',activity:'5月27日 课程学习',risk:'低于阈值',crest:'grayc'},
{name:'东嘎街道小学',code:'XZDL0009',level:'小学',state:'expiring',status:'即将到期',plan:'基础套餐',dates:'2023-05-01 ~ 2024-06-10',remain:'剩余 10 天',nums:'754 / 46 / 11',activity:'5月25日 课程学习',risk:'低于阈值',crest:'greenc'}];
const nav=['⌂|驾驶舱','▰|学校管理','♙|用户管理','▥|课程管理','⌘|测评管理','♙|志愿者管理','▤|套餐管理','✎|内容审核','◇|隐私与合规','⚙|系统运维','▧|审计日志','⇧|数据导出','⚙|设置'];
document.querySelector('#nav').innerHTML=nav.map((x,i)=>{let[a,b]=x.split('|');return `<a class="${i===1?'active':''}"><i>${a}</i><span>${b}</span>${i===7?'<b>5</b>':''}</a>`}).join('');
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function normalize(row){const active=row.isActive!==false;return {name:row.name,code:row.code,level:'—',state:active?'normal':'stopped',status:active?'正常运营':'停用',plan:'—',dates:'—',remain:active?'运行中':'已停用',nums:`${row.counts?.memberships??0} / — / —`,activity:'—',risk:'—',crest:active?'greenc':'grayc',region:row.regionCode||'—',id:row.id};}
function render(){let q=document.querySelector('#search').value.trim(),st=document.querySelector('#status').value,lv=document.querySelector('#stage').value,p=document.querySelector('#plan').value;let list=schools.filter(s=>(!q||s.name.includes(q)||s.code.includes(q))&&(st==='all'||s.state===st)&&(lv==='all'||s.level===lv)&&(p==='all'||s.plan===p));
 document.querySelector('#tracks').innerHTML=loadError?`<div class="load-error">${esc(loadError)}</div>`:list.slice(0,5).map(s=>`<div class="school-row cols"><div class="school"><span class="crest ${esc(s.crest)}">校</span><div><strong>${esc(s.name)}</strong><small>学校编码：${esc(s.code)}<span class="tag level">${esc(s.level)}</span></small></div></div><span class="tag ${esc(s.state)}">● ${esc(s.status)}</span><span>◉ ${esc(s.plan)}</span><span class="service">${esc(s.dates)}<br><i class="${s.state==='stopped'?'bad':'remain'}">${esc(s.remain)}</i></span><span>${esc(s.nums)}</span><span>${esc(s.activity)}</span><span class="risk warn">● ${esc(s.risk)}</span><button class="detail" data-name="${esc(s.name)}">查看详情</button></div>`).join('')||'<div style="padding:40px;text-align:center;color:#888">暂无匹配学校</div>';
 document.querySelector('#tbody').innerHTML=list.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.code)}</td><td>${esc(s.region)}</td><td>${esc(s.level)}</td><td><span class="tag ${esc(s.state)}">● ${esc(s.status)}</span></td><td>${esc(s.plan)}</td><td>${esc(s.dates)}</td><td>${esc((s.nums||'—').split(' / ')[0])}</td><td>—</td><td>—</td><td>${esc(s.activity)}</td><td class="ops"><button class="detail" data-name="${esc(s.name)}" data-id="${esc(s.id||'')}">查看详情</button><button class="edit" data-id="${esc(s.id||'')}" data-name="${esc(s.name)}" data-code="${esc(s.code)}">编辑</button><button>更多⌄</button></td></tr>`).join('');
 document.querySelectorAll('.detail').forEach(b=>b.onclick=()=>open('学校详情',`${b.dataset.name} 的信息、服务期、人员规模和运营风险。`));}
function toast(t){let e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function open(t,x,mode='info',school=null){document.querySelector('#mtitle').textContent=t;document.querySelector('#mtext').textContent=x;const inputs=document.querySelectorAll('#modal input');inputs[0].value=school?.name||'';inputs[1].value=school?.code||'';document.querySelector('#modal').dataset.mode=mode;document.querySelector('#modal').dataset.id=school?.id||'';document.querySelector('#modal').hidden=false}
async function loadSchools(){loadError='';render();try{const result=await window.YuzanApi.listAdminSchools({limit:100});schools=(result.items||[]).map(normalize);if(!schools.length)loadError='暂无学校数据';}catch(error){loadError=error?.message||'学校列表加载失败，请检查登录状态或服务连接';}render();}
document.querySelector('#query').onclick=render;document.querySelector('#search').oninput=render;document.querySelector('#clear').onclick=()=>{document.querySelector('#search').value='';document.querySelector('#status').value='all';document.querySelector('#stage').value='all';document.querySelector('#plan').value='all';render();toast('筛选条件已清空')};document.querySelector('#add').onclick=()=>open('新增学校','填写学校名称和唯一编码后提交。','create');document.querySelector('#import').onclick=()=>open('批量导入','请使用学校导入页提交 JSON 行数据，导入结果会保留逐行错误。','info');['close','cancel'].forEach(id=>document.querySelector('#'+id).onclick=()=>document.querySelector('#modal').hidden=true);document.querySelector('#confirm').onclick=async()=>{const modal=document.querySelector('#modal');const inputs=modal.querySelectorAll('input');try{if(modal.dataset.mode==='create'){await YuzanApi.createAdminSchool({name:inputs[0].value.trim(),code:inputs[1].value.trim()});toast('学校已创建');}else if(modal.dataset.mode==='edit'){await YuzanApi.updateAdminSchool(modal.dataset.id,{name:inputs[0].value.trim(),code:inputs[1].value.trim()});toast('学校已更新');}else{modal.hidden=true;return;}modal.hidden=true;await loadSchools();}catch(error){toast(error.message||'保存失败');}};document.querySelector('#tbody').addEventListener('click',e=>{const edit=e.target.closest('.edit');if(edit)open('编辑学校','修改后将写入审计日志。','edit',{id:edit.dataset.id,name:edit.dataset.name,code:edit.dataset.code});});document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast('已切换到'+b.textContent)});loadSchools();
