packages:
  - backend/*
  - frontend
  - packages/*
  - infra/database

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/engines"
  - core-js
  - esbuild
  - prisma
  - protobufjs
  - unrs-resolver
