import type {
  AssessmentTask,
  MaterialOption,
  StudentAssessmentReport,
  TargetOption,
} from "./types";

const qrReason =
  "二维码生成待依赖批准：当前任务范围不允许新增依赖，也不展示伪二维码。";

export const readingMaterials: MaterialOption[] = [
  {
    id: "reading-snowline",
    title: "朗读材料：雪线下的清晨",
    summary: "关注停连、重音和自然语速，适合六年级口语测评。",
    type: "reading",
    level: "六年级",
    estimatedMinutes: 8,
  },
  {
    id: "reading-market",
    title: "朗读材料：集市上的问候",
    summary: "用于练习连续问答中的语气变化与礼貌表达。",
    type: "reading",
    level: "五年级",
    estimatedMinutes: 6,
  },
  {
    id: "reading-river",
    title: "朗读材料：河谷里的风",
    summary: "适合观察学生在长句中的呼吸与节奏控制。",
    type: "reading",
    level: "七年级",
    estimatedMinutes: 10,
  },
];

export const writingTasks: MaterialOption[] = [
  {
    id: "writing-letter",
    title: "书面任务：给远方同学的一封信",
    summary: "检查书写结构、礼貌用语和主题完整度。",
    type: "writing",
    level: "六年级",
    estimatedMinutes: 20,
  },
  {
    id: "writing-diary",
    title: "书面任务：周三校园日记",
    summary: "关注细节描写与句子连贯性。",
    type: "writing",
    level: "五年级",
    estimatedMinutes: 18,
  },
  {
    id: "writing-compare",
    title: "书面任务：今昔家乡对比",
    summary: "评估比较结构、连接词和观点表达。",
    type: "writing",
    level: "七年级",
    estimatedMinutes: 24,
  },
];

export const targetOptions: TargetOption[] = [
  {
    id: "school-lhasa-experimental",
    name: "拉萨实验学校",
    kind: "school",
    description: "覆盖试点校内已接入 demo 的学生样本。",
    studentIds: ["student-lobsang", "student-tsering", "student-dechen"],
  },
  {
    id: "class-grade6-b2",
    name: "六年级二班",
    kind: "class",
    description: "班级样本包含 3 名学生，便于教师演示管理流程。",
    studentIds: ["student-lobsang", "student-tsering", "student-dechen"],
  },
  {
    id: "class-grade5-a1",
    name: "五年级一班",
    kind: "class",
    description: "用于预览跨班级创建测评任务的目标配置。",
    studentIds: ["student-dawa", "student-nyima"],
  },
  {
    id: "student-lobsang",
    name: "洛桑",
    kind: "student",
    description: "六年级二班，适合查看完整历史对比。",
    studentIds: ["student-lobsang"],
  },
  {
    id: "student-tsering",
    name: "次仁",
    kind: "student",
    description: "六年级二班，报告状态为生成中。",
    studentIds: ["student-tsering"],
  },
  {
    id: "student-dechen",
    name: "德庆",
    kind: "student",
    description: "六年级二班，报告暂不可用。",
    studentIds: ["student-dechen"],
  },
];

export const studentReports: Record<string, StudentAssessmentReport> = {
  "student-lobsang": {
    studentId: "student-lobsang",
    studentName: "洛桑",
    className: "六年级二班",
    schoolName: "拉萨实验学校",
    status: "ready",
    latest: {
      id: "report-lobsang-2026-07-03",
      assessedAt: "2026-07-03T09:10:00+08:00",
      fluencyScore: 88,
      expressionScore: 82,
      writingScore: 85,
      summary: "朗读节奏稳定，书面表达结构完整，口头重音仍可更自然。",
      strengths: ["长句停连更稳", "书面段落结构完整", "能主动修正个别读音"],
      nextStep: "继续练习人物对话中的语气起伏，并补强结尾总结句。",
    },
    history: [
      {
        id: "report-lobsang-2026-07-03",
        assessedAt: "2026-07-03T09:10:00+08:00",
        fluencyScore: 88,
        expressionScore: 82,
        writingScore: 85,
        summary: "朗读节奏稳定，书面表达结构完整，口头重音仍可更自然。",
        strengths: ["长句停连更稳", "书面段落结构完整", "能主动修正个别读音"],
        nextStep: "继续练习人物对话中的语气起伏，并补强结尾总结句。",
      },
      {
        id: "report-lobsang-2026-06-12",
        assessedAt: "2026-06-12T14:20:00+08:00",
        fluencyScore: 81,
        expressionScore: 78,
        writingScore: 80,
        summary: "朗读完成度提升明显，但换气点和连接词使用还不够稳定。",
        strengths: ["敢于完整朗读", "书写清晰", "能围绕主题作答"],
        nextStep: "重点练习逗号停顿与“因为/所以”等连接词。",
      },
      {
        id: "report-lobsang-2026-05-07",
        assessedAt: "2026-05-07T11:40:00+08:00",
        fluencyScore: 74,
        expressionScore: 72,
        writingScore: 76,
        summary: "朗读基本完成，部分长句仍有断裂，书面表达较依赖模板。",
        strengths: ["发音较清晰", "能完成基础结构", "愿意复读修正"],
        nextStep: "通过跟读练习稳定语速，并增加个人感受句。",
      },
    ],
    comparisonSummary:
      "较 2026-06-12 最近一次测评，朗读流利度 +7，表达力 +4，书面任务 +5。",
  },
  "student-tsering": {
    studentId: "student-tsering",
    studentName: "次仁",
    className: "六年级二班",
    schoolName: "拉萨实验学校",
    status: "in_progress",
    latest: null,
    history: [],
    comparisonSummary: "demo 报告生成中，历史对比暂不可用。",
  },
  "student-dechen": {
    studentId: "student-dechen",
    studentName: "德庆",
    className: "六年级二班",
    schoolName: "拉萨实验学校",
    status: "unavailable",
    latest: null,
    history: [],
    comparisonSummary: "demo 数据不可用，待真实 Assessment API 接入后提供。",
  },
  "student-dawa": {
    studentId: "student-dawa",
    studentName: "达瓦",
    className: "五年级一班",
    schoolName: "拉萨实验学校",
    status: "ready",
    latest: {
      id: "report-dawa-2026-06-28",
      assessedAt: "2026-06-28T16:00:00+08:00",
      fluencyScore: 79,
      expressionScore: 77,
      writingScore: 83,
      summary: "叙事结构清楚，朗读抑扬尚可，结尾收束需要更明确。",
      strengths: ["叙事顺序清楚", "能保持稳定音量", "书面细节较完整"],
      nextStep: "把结尾观点句说完整，并控制段落过渡。",
    },
    history: [
      {
        id: "report-dawa-2026-06-28",
        assessedAt: "2026-06-28T16:00:00+08:00",
        fluencyScore: 79,
        expressionScore: 77,
        writingScore: 83,
        summary: "叙事结构清楚，朗读抑扬尚可，结尾收束需要更明确。",
        strengths: ["叙事顺序清楚", "能保持稳定音量", "书面细节较完整"],
        nextStep: "把结尾观点句说完整，并控制段落过渡。",
      },
      {
        id: "report-dawa-2026-05-20",
        assessedAt: "2026-05-20T10:15:00+08:00",
        fluencyScore: 73,
        expressionScore: 72,
        writingScore: 78,
        summary: "完成度良好，但个别长句易停顿，书面过渡语较少。",
        strengths: ["主题清楚", "愿意自我纠正", "卷面整洁"],
        nextStep: "练习“先…再…最后…”的过渡表达。",
      },
    ],
    comparisonSummary:
      "较 2026-05-20 最近一次测评，朗读流利度 +6，表达力 +5，书面任务 +5。",
  },
  "student-nyima": {
    studentId: "student-nyima",
    studentName: "尼玛",
    className: "五年级一班",
    schoolName: "拉萨实验学校",
    status: "unavailable",
    latest: null,
    history: [],
    comparisonSummary: "demo 数据不可用，待真实 Assessment API 接入后提供。",
  },
};

export const assessmentTasks: AssessmentTask[] = [
  {
    id: "assessment-demo-summer-speaking",
    title: "七月朗读与书面表达联合测评",
    readingMaterialId: "reading-snowline",
    writingTaskId: "writing-letter",
    opensAt: "2026-07-10T08:00",
    closesAt: "2026-07-15T20:00",
    targetIds: ["school-lhasa-experimental", "class-grade6-b2"],
    targetSummary: "拉萨实验学校 · 六年级二班 · 3 名学生（demo）",
    anonymous: false,
    status: "live",
    demoLink: {
      url: "https://demo.yuzan-next.local/assessment/assessment-demo-summer-speaking",
      code: "summer-speaking",
      qrAvailable: false,
      qrReason,
    },
    progress: {
      completedLabel: "demo",
      incompleteLabel: "unavailable",
      note: "真实完成/未完成人数待 Assessment API 接入后提供。",
    },
    reportStudentIds: ["student-lobsang", "student-tsering", "student-dechen"],
    createdBy: "次仁老师",
    createdAt: "2026-07-08T18:20:00+08:00",
  },
  {
    id: "assessment-demo-writing-followup",
    title: "家乡变化书面任务复测",
    readingMaterialId: "reading-river",
    writingTaskId: "writing-compare",
    opensAt: "2026-07-18T08:30",
    closesAt: "2026-07-23T18:30",
    targetIds: ["class-grade5-a1", "student-dawa"],
    targetSummary: "五年级一班 · 达瓦等 2 名学生（demo）",
    anonymous: true,
    status: "scheduled",
    demoLink: {
      url: "https://demo.yuzan-next.local/assessment/assessment-demo-writing-followup",
      code: "writing-followup",
      qrAvailable: false,
      qrReason,
    },
    progress: {
      completedLabel: "demo",
      incompleteLabel: "unavailable",
      note: "当前仅展示任务管理流程，不伪造真实班级人数。",
    },
    reportStudentIds: ["student-dawa", "student-nyima"],
    createdBy: "边珍老师",
    createdAt: "2026-07-06T10:05:00+08:00",
  },
];
