#!/usr/bin/env node
import { createHash } from "node:crypto";
import { execFile } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import sharp from "sharp";

const exec = promisify(execFile);
const root = path.resolve(import.meta.dirname, "../..");
const defaults = { questions:path.join(root,"local_sources/question-bank/题库【三改】.docx"), answers:path.join(root,"local_sources/question-bank/答案及评分细则.docx"), media:path.join(root,"local_sources/question-bank/题库音频及图片.zip"), output:path.join(root,"local_sources/question-bank/.generated") };
const cn={一:1,二:2,三:3,四:4,五:5,六:6};
const families=[["听音选图","LISTEN_IMAGE_CHOICE","LISTEN"],["听写句子","DICTATION","LISTEN"],["朗读句子","READ_ALOUD","SPEAK"],["看图说话","PICTURE_SPEAKING","SPEAK"],["单词认读","WORD_RECOGNITION","READ"],["句子理解","SENTENCE_COMPREHENSION","READ"],["看图写词","PICTURE_WORD","WRITE"],["句子补全","SENTENCE_COMPLETION","WRITE"],["句式改写","SENTENCE_COMPLETION","WRITE"]];
const expected={LISTEN_IMAGE_CHOICE:[3,3],DICTATION:[3,5],READ_ALOUD:[3,4],PICTURE_SPEAKING:[1,14],WORD_RECOGNITION:[3,4],SENTENCE_COMPREHENSION:[3,4],PICTURE_WORD:[2,5],SENTENCE_COMPLETION:[2,8]};
const hash=b=>createHash("sha256").update(b).digest("hex");
const plain=x=>x.replace(/<w:tab\/>/g," ").replace(/<w:t[^>]*>([\s\S]*?)<\/w:t>/g,"$1").replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").replace(/\s+/g," ").trim();
const add=(xs,severity,code,detail={})=>xs.push({severity,code,...detail});
async function names(file){const {stdout}=await exec("unzip",["-Z1",file],{maxBuffer:32e6});return stdout.split(/\r?\n/).filter(Boolean)}
async function read(file,name){const {stdout}=await exec("unzip",["-p",file,name],{encoding:"buffer",maxBuffer:128e6});return stdout}
async function docx(file){const [xml,rels]=await Promise.all([read(file,"word/document.xml"),read(file,"word/_rels/document.xml.rels")]);const map=Object.fromEntries([...rels.toString().matchAll(/Id="([^"]+)"[^>]*Target="([^"]+)"/g)].map(([,a,b])=>[a,path.posix.normalize(path.posix.join("word",b))]));const paragraphs=[...xml.toString().matchAll(/<w:p\b[\s\S]*?<\/w:p>/g)].map((m,index)=>({index,text:plain(m[0]),rids:[...m[0].matchAll(/r:embed="([^"]+)"/g)].map(x=>x[1])}));const occurrences=[];for(const p of paragraphs)for(const rid of p.rids)occurrences.push({occurrence:occurrences.length+1,paragraph:p.index,rid,entry:map[rid]});return{paragraphs,occurrences}}
function levels(paras){return paras.map((p,i)=>({i,level:cn[(p.text.match(/水平([一二三四五六])级/)||[])[1]]})).filter(x=>x.level)}
function strategy(f){return({LISTEN_IMAGE_CHOICE:"EXACT_CHOICE",DICTATION:"DICTATION_ALIGNMENT",READ_ALOUD:"SPEECH_READING",PICTURE_SPEAKING:"SPEECH_OPEN_RESPONSE",WORD_RECOGNITION:"EXACT_CHOICE",SENTENCE_COMPREHENSION:"EXACT_CHOICE",PICTURE_WORD:"ACCEPTED_TEXT",SENTENCE_COMPLETION:"RUBRIC_TEXT"})[f]}
function item(level,b,n,content,rids=[]){const e=expected[b.family];const choice=["LISTEN_IMAGE_CHOICE","WORD_RECOGNITION","SENTENCE_COMPREHENSION"].includes(b.family);const speech=["READ_ALOUD","PICTURE_SPEAKING"].includes(b.family);const visual=["PICTURE_SPEAKING","PICTURE_WORD"].includes(b.family);return{stableKey:`L${level}-${b.domain}-${b.family}-${String(n).padStart(3,"0")}`,level,domain:b.domain,family:b.family,sourceOrder:n,maxScore:e[1],deliverySpec:{instruction:b.label,stimulus:visual?{type:"IMAGE"}:b.domain==="LISTEN"?{type:"AUDIO"}:{type:"TEXT",promptText:typeof content==="string"?content:content.prompt},response:choice?{type:"CHOICE",options:content.options||rids.map((rid,i)=>({key:"ABCD"[i],sourceWordImage:rid}))}:speech?{type:"SPEECH"}:{type:"TEXT"}},scoringSpec:{strategy:strategy(b.family),maxScore:e[1]},mediaBindings:{imageRids:rids},sourceTrace:{questionDocx:{familyLabel:b.label,sourceOrder:n}}}}
function parse(doc){const starts=levels(doc.paragraphs),out=[];for(const {i:start,level} of starts){const end=starts.find(x=>x.i>start)?.i??doc.paragraphs.length,bs=[];for(let i=start+1;i<end;i++){const f=families.find(x=>doc.paragraphs[i].text.includes(x[0]));if(f)bs.push({start:i,end,label:f[0],family:f[1],domain:f[2]})}for(let i=0;i<bs.length;i++)bs[i].end=bs[i+1]?.start??end;const qs=[];for(const b of bs){const ps=doc.paragraphs.slice(b.start+1,b.end),lines=ps.map(p=>p.text).filter(Boolean),put=(c,n,r=[])=>qs.push(item(level,b,n,c,r));if(b.family==="LISTEN_IMAGE_CHOICE"){let n=0;for(let i=0;i<ps.length;i++)if(/音频[：:]/.test(ps[i].text)){n++;const next=ps.slice(i+1).findIndex(p=>/音频[：:]/.test(p.text)),group=ps.slice(i,next<0?ps.length:i+1+next);put(ps[i].text,n,group.flatMap(p=>p.rids))}}else if(["DICTATION","READ_ALOUD"].includes(b.family))lines.filter(x=>x.length>=5&&!/每道|分[）)]/.test(x)).forEach((x,n)=>put(x.replace(/^\d+[.、]\s*/,""),n+1));else if(b.family==="PICTURE_SPEAKING")put(lines.join(" "),1,ps.flatMap(p=>p.rids));else if(["WORD_RECOGNITION","SENTENCE_COMPREHENSION"].includes(b.family)){let prompt="",options=[];const flush=()=>{if(prompt&&options.length)put({prompt,options},qs.filter(q=>q.family===b.family).length+1),prompt="",options=[]};for(const x of lines){const m=x.match(/^([A-D])[.．、]\s*(.+)/);if(m)options.push({key:m[1],text:m[2]});else{flush();prompt=x.replace(/^\d+[.、]\s*/,"")}}flush()}else if(b.family==="PICTURE_WORD")ps.filter(p=>p.rids.length).forEach((p,n)=>put(lines[n]||"根据图片提示作答",n+1,p.rids));else if(b.family==="SENTENCE_COMPLETION")lines.filter(x=>/^\d+[.、]/.test(x)).forEach((x,n)=>put(x,n+1))}out.push({level,sections:["LISTEN","SPEAK","READ","WRITE"].map(domain=>({domain,families:qs.filter(q=>q.domain===domain)})),questions:qs})}return out}
async function inventory(zip){const result=[];for(const zipPath of (await names(zip)).filter(x=>!x.endsWith("/"))){const buf=await read(zip,zipPath),extension=path.extname(zipPath).slice(1).toLowerCase(),mediaType=["jpg","jpeg","png"].includes(extension)?"IMAGE":["mp3","wav","m4a"].includes(extension)?"AUDIO":"OTHER",level=cn[(zipPath.match(/水平([一二三四五六])级/)||[])[1]];result.push({zipPath,filename:path.basename(zipPath),extension,size:buf.length,mediaType,level,sha256:hash(buf)})}return result}
async function fp(buf){const {data}=await sharp(buf).resize(16,16,{fit:"fill"}).grayscale().raw().toBuffer({resolveWithObject:true});const avg=data.reduce((a,x)=>a+x,0)/data.length;return[...data].map(x=>x>=avg?1:0)}
const hamming=(a,b)=>a.reduce((n,x,i)=>n+(x!==b[i]),0);
async function mediaBind(levels,doc,options,media,issues){const words=[];for(const o of doc.occurrences)if(o.entry){const b=await read(options.questions,o.entry);words.push({...o,sha256:hash(b),fp:await fp(b)})}const images=media.filter(x=>x.mediaType==="IMAGE");const fps=new Map;for(const m of images)fps.set(m.zipPath,await fp(await read(options.media,m.zipPath)));for(const l of levels)for(const q of l.questions){const found=[];for(const rid of q.mediaBindings.imageRids){const w=words.find(x=>x.rid===rid);if(!w)continue;let ranked=images.map(x=>({x,d:x.sha256===w.sha256?0:hamming(w.fp,fps.get(x.zipPath))})).sort((a,b)=>a.d-b.d);if(!ranked.length||ranked[0].d>30||(ranked[1]&&ranked[0].d+2>=ranked[1].d)){add(issues,"ERROR",ranked.length?"IMAGE_AMBIGUOUS":"IMAGE_UNMATCHED",{level:q.level,family:q.family,sourceOccurrence:w.occurrence});continue}found.push({kind:"IMAGE",zipPath:ranked[0].x.zipPath,sha256:ranked[0].x.sha256,sourceOccurrence:w.occurrence,match:ranked[0].d===0?"exact":"perceptual"})}q.mediaBindings.images=found;delete q.mediaBindings.imageRids;if(["LISTEN_IMAGE_CHOICE","DICTATION"].includes(q.family)){const scope=q.family==="DICTATION"?"听写句子":"听音选图",a=media.filter(x=>x.mediaType==="AUDIO"&&x.level===q.level&&x.zipPath.includes(scope)&&new RegExp(`/${q.sourceOrder}[.．]?`).test(x.zipPath));if(a.length!==1)add(issues,"ERROR",a.length?"AUDIO_AMBIGUOUS":"MEDIA_MISSING",{level:q.level,family:q.family,sourceOrder:q.sourceOrder});else q.mediaBindings.audio={kind:"AUDIO",zipPath:a[0].zipPath,sha256:a[0].sha256}}}return words}
function validate(levels,issues){for(const l of levels){for(const [family,[count]] of Object.entries(expected)){const actual=l.questions.filter(q=>q.family===family).length;if(actual!==count)add(issues,"ERROR","QUESTION_COUNT_MISMATCH",{level:l.level,family,expected:count,actual})}const total=l.questions.reduce((n,q)=>n+q.maxScore,0);if(total!==100)add(issues,"ERROR","POINT_TOTAL_MISMATCH",{level:l.level,expected:100,actual:total});for(const q of l.questions)if(/correctanswer|acceptedanswers|referenceanswer|rubric|scoringspec/i.test(JSON.stringify(q.deliverySpec)))add(issues,"ERROR","DELIVERY_SCORING_LEAK",{level:q.level,family:q.family})}}
function args(xs){const a={...defaults};for(let i=0;i<xs.length;i++)if(xs[i]==="--all")a.all=true;else if(xs[i]==="--level")a.level=Number(xs[++i]);return a}
export async function run(options=args(process.argv.slice(2))){const issues=[],[questions,answers,media]=await Promise.all([docx(options.questions),docx(options.answers),inventory(options.media)]),all=parse(questions);await mediaBind(all,questions,options,media,issues);validate(all,issues);const chosen=options.level?all.filter(x=>x.level===options.level):all,relevant=issues.filter(x=>!options.level||x.level===options.level),report={mode:"DRY RUN — NO DATABASE WRITE — NO MINIO WRITE",questionDocx:{levels:all.length,embeddedImages:questions.occurrences.length},answerDocx:{levels:levels(answers.paragraphs).length},media:{totalFiles:media.length,images:media.filter(x=>x.mediaType==="IMAGE").length,audio:media.filter(x=>x.mediaType==="AUDIO").length,byLevel:Object.fromEntries([1,2,3,4,5,6].map(level=>[level,{images:media.filter(x=>x.level===level&&x.mediaType==="IMAGE").length,audio:media.filter(x=>x.level===level&&x.mediaType==="AUDIO").length}]))},validation:{errors:relevant.filter(x=>x.severity==="ERROR").length,warnings:relevant.filter(x=>x.severity==="WARNING").length},issues:relevant};await mkdir(options.output,{recursive:true});await Promise.all([writeFile(path.join(options.output,"manifest.json"),JSON.stringify({schemaVersion:1,source:{questions:options.questions,answers:options.answers,media:options.media},levels:chosen,issues:relevant},null,2)),writeFile(path.join(options.output,"validation-report.json"),JSON.stringify(report,null,2)),writeFile(path.join(options.output,"media-inventory.json"),JSON.stringify(media,null,2))]);console.log(`QB source validator\n${report.mode}\nQuestions: ${all.length} levels, ${all.reduce((n,x)=>n+x.questions.length,0)} items, ${questions.occurrences.length} embedded images\nMedia: ${report.media.totalFiles} files (${report.media.images} images, ${report.media.audio} audio)\nValidation: errors ${report.validation.errors}, warnings ${report.validation.warnings}`);for(const x of relevant.filter(x=>x.severity==="ERROR"))console.log(`ERROR L${x.level??"?"} / ${x.family??"SOURCE"} ${x.code}${x.expected!==undefined?` expected ${x.expected} actual ${x.actual}`:""}`);return{report}}
const parseQuestionDocument=parse;
parse=(doc)=>{const parsed=parseQuestionDocument(doc),starts=levels(doc.paragraphs);for(const level of parsed){const start=starts.find(x=>x.level===level.level)?.i;if(start===undefined)continue;const end=starts.find(x=>x.i>start)?.i??doc.paragraphs.length;for(let i=start;i<end;i++){if(!/句子补全|句式改写/.test(doc.paragraphs[i].text))continue;const next=doc.paragraphs.slice(i+1,end).findIndex(p=>families.some(f=>p.text.includes(f[0]))),lines=doc.paragraphs.slice(i+1,next<0?end:i+1+next).map(p=>p.text).filter(Boolean);if(level.questions.some(q=>q.family==="SENTENCE_COMPLETION"))continue;const pivot=lines.findIndex(x=>/照样子|请仿照/.test(x));if(pivot<=0)continue;const block={label:doc.paragraphs[i].text,family:"SENTENCE_COMPLETION",domain:"WRITE"};level.questions.push(item(level.level,block,1,lines.slice(0,pivot).join(" ")),item(level.level,block,2,lines.slice(pivot).join(" ")));level.sections.find(x=>x.domain==="WRITE").families=level.questions.filter(q=>q.domain==="WRITE")}}return parsed};
if(import.meta.main)run().then(({report})=>process.exitCode=report.validation.errors?1:0).catch(e=>{console.error(e);process.exitCode=1});
