/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 存活探针 */
    get: operations["getLiveness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 就绪探针 */
    get: operations["getReadiness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 用户登录 */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 刷新会话 */
    post: operations["refreshSession"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 退出登录 */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取当前用户 */
    get: operations["getCurrentUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/schools/{schoolId}/course-versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出课程版本 */
    get: operations["listCourseVersions"];
    put?: never;
    /** 创建课程草稿 */
    post: operations["createCourseDraft"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/schools/{schoolId}/course-versions/{courseVersionId}:publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 发布课程版本 */
    post: operations["publishCourseVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/schools/{schoolId}/classes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出班级 */
    get: operations["listClasses"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/schools/{schoolId}/assignments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 布置任务 */
    post: operations["createAssignment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/schools/{schoolId}/assignments/{assignmentId}:open": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 开放任务 */
    post: operations["openAssignment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/schools/{schoolId}/students/me/today": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取学生今日任务 */
    get: operations["getMyTodayTasks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/schools/{schoolId}/activities/{activityId}/progress": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** 保存活动进度 */
    put: operations["saveActivityProgress"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/schools/{schoolId}/assignments/{assignmentId}/submissions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 提交任务答案 */
    post: operations["submitAssignment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/schools/{schoolId}/submissions/{submissionId}/feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 发布教师反馈 */
    post: operations["releaseFeedback"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/schools/{schoolId}/sync/push": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 推送离线同步操作 */
    post: operations["pushSyncOperations"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/schools/{schoolId}/sync/pull": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 拉取增量变更 */
    get: operations["pullSyncChanges"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @example {
     *       "requestId": "00000000-0000-0000-0000-000000000001",
     *       "nextCursor": null,
     *       "hasMore": false
     *     }
     */
    EnvelopeMeta: {
      /** Format: uuid */
      requestId: string;
      nextCursor?: string | null;
      hasMore?: boolean;
    };
    ErrorBody: {
      code: string;
      message: string;
      details?: {
        [key: string]: string | number | boolean | null | string[];
      };
      /** Format: uuid */
      requestId: string;
    };
    /**
     * @example {
     *       "error": {
     *         "code": "ASSIGNMENT_NOT_OPEN",
     *         "message": "当前任务尚未开放",
     *         "details": {
     *           "assignmentId": "11111111-1111-1111-1111-111111111111"
     *         },
     *         "requestId": "00000000-0000-0000-0000-000000000003"
     *       }
     *     }
     */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    Health: {
      /** @enum {string} */
      status: "ok" | "degraded";
      /** Format: date-time */
      timestamp: string;
    };
    HealthResponse: {
      data: components["schemas"]["Health"];
      meta: components["schemas"]["EnvelopeMeta"];
    };
    LoginRequest: {
      identifier: string;
      password: string;
    };
    Membership: {
      /** Format: uuid */
      schoolId: string;
      schoolName: string;
      /** @enum {string} */
      role:
        | "STUDENT"
        | "TEACHER"
        | "RESEARCHER"
        | "SCHOOL_ADMIN"
        | "PLATFORM_ADMIN";
    };
    CurrentUser: {
      /** Format: uuid */
      id: string;
      displayName: string;
      /** @default zh-CN */
      preferredLocale: string;
      memberships: components["schemas"]["Membership"][];
    };
    AuthSession: {
      accessToken: string;
      expiresIn: number;
      user: components["schemas"]["CurrentUser"];
    };
    AuthSessionResponse: {
      data: components["schemas"]["AuthSession"];
      meta: components["schemas"]["EnvelopeMeta"];
    };
    CurrentUserResponse: {
      data: components["schemas"]["CurrentUser"];
      meta: components["schemas"]["EnvelopeMeta"];
    };
    /** @enum {string} */
    CourseVersionStatus:
      | "DRAFT"
      | "IN_REVIEW"
      | "CHANGES_REQUESTED"
      | "APPROVED"
      | "PUBLISHED"
      | "RETIRED";
    CourseVersionSummary: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      courseId: string;
      version: number;
      title: string;
      status: components["schemas"]["CourseVersionStatus"];
      gradeBand?: string | null;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseVersionListResponse: {
      data: components["schemas"]["CourseVersionSummary"][];
      meta: components["schemas"]["EnvelopeMeta"];
    };
    CreateCourseDraftRequest: {
      title: string;
      description?: string;
      gradeBand?: string;
      /** @default zh-CN */
      locale: string;
    };
    CourseVersionResponse: {
      data: components["schemas"]["CourseVersionSummary"];
      meta: components["schemas"]["EnvelopeMeta"];
    };
    ClassSummary: {
      /** Format: uuid */
      id: string;
      name: string;
      grade: string;
      studentCount: number;
    };
    ClassListResponse: {
      data: components["schemas"]["ClassSummary"][];
      meta: components["schemas"]["EnvelopeMeta"];
    };
    /** @enum {string} */
    AssignmentStatus:
      "DRAFT" | "SCHEDULED" | "OPEN" | "CLOSED" | "CANCELLED" | "ARCHIVED";
    CreateAssignmentRequest: {
      /** Format: uuid */
      classId: string;
      /** Format: uuid */
      courseVersionId: string;
      title: string;
      /** Format: date-time */
      startsAt: string;
      /** Format: date-time */
      dueAt: string;
      /** @default false */
      offlineRequired: boolean;
    };
    Assignment: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      classId: string;
      /** Format: uuid */
      courseVersionId: string;
      title: string;
      status: components["schemas"]["AssignmentStatus"];
      /** Format: date-time */
      startsAt: string;
      /** Format: date-time */
      dueAt: string;
      revision: number;
      offlineRequired?: boolean;
    };
    AssignmentResponse: {
      data: components["schemas"]["Assignment"];
      meta: components["schemas"]["EnvelopeMeta"];
    };
    TodayTask: components["schemas"]["Assignment"] & {
      /** @enum {string} */
      progressStatus:
        | "NOT_STARTED"
        | "IN_PROGRESS"
        | "PENDING_SYNC"
        | "SUBMITTED"
        | "REVIEWED";
      /** @enum {string} */
      downloadStatus:
        "NOT_REQUIRED" | "NOT_DOWNLOADED" | "DOWNLOADING" | "READY" | "FAILED";
    };
    TodayTasksResponse: {
      data: components["schemas"]["TodayTask"][];
      meta: components["schemas"]["EnvelopeMeta"];
    };
    SaveProgressRequest: {
      position: number;
      completed: boolean;
      /** Format: date-time */
      clientUpdatedAt?: string;
    };
    Progress: {
      /** Format: uuid */
      activityId: string;
      position: number;
      completed: boolean;
      revision: number;
      /** Format: date-time */
      updatedAt: string;
    };
    ProgressResponse: {
      data: components["schemas"]["Progress"];
      meta: components["schemas"]["EnvelopeMeta"];
    };
    AnswerInput: {
      /** Format: uuid */
      activityId: string;
      /** @enum {string} */
      kind: "CHOICE" | "TEXT" | "SPEECH";
      /** @description 答案内容占位类型，具体按 CHOICE/TEXT/SPEECH 的结构化形态待领域模型确认 */
      value?:
        string | number | boolean | unknown[] | Record<string, never> | null;
      /** Format: uuid */
      audioAssetId?: string | null;
    };
    SubmitAssignmentRequest: {
      attemptNo: number;
      /** Format: uuid */
      deviceId?: string | null;
      answers: components["schemas"]["AnswerInput"][];
    };
    Submission: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      assignmentId: string;
      /** @enum {string} */
      status:
        | "SUBMITTED"
        | "PROCESSING"
        | "NEEDS_REVIEW"
        | "REVIEWED"
        | "RETURNED"
        | "ACCEPTED";
      attemptNo: number;
      revision: number;
      /** Format: date-time */
      submittedAt: string;
    };
    SubmissionResponse: {
      data: components["schemas"]["Submission"];
      meta: components["schemas"]["EnvelopeMeta"];
    };
    ReleaseFeedbackRequest: {
      /** @enum {string} */
      decision: "ACCEPT" | "RETURN";
      comment: string;
      score?: number | null;
    };
    Feedback: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      submissionId: string;
      /** @enum {string} */
      decision: "ACCEPT" | "RETURN";
      comment: string;
      score?: number | null;
      /** Format: date-time */
      releasedAt: string;
      revision: number;
    };
    FeedbackResponse: {
      data: components["schemas"]["Feedback"];
      meta: components["schemas"]["EnvelopeMeta"];
    };
    SyncOperation: {
      /** Format: uuid */
      operationId: string;
      entityType: string;
      entityId: string;
      action: string;
      baseRevision?: number | null;
      payload: components["schemas"]["SyncPayload"];
      /** Format: date-time */
      createdAt: string;
    };
    SyncPushRequest: {
      /** Format: uuid */
      deviceId: string;
      operations: components["schemas"]["SyncOperation"][];
    };
    SyncReceipt: {
      /** Format: uuid */
      operationId: string;
      /** @enum {string} */
      status: "ACKNOWLEDGED" | "CONFLICT" | "PERMANENT_FAILURE";
      serverRevision?: number | null;
      errorCode?: string | null;
    };
    SyncPushResponse: {
      data: components["schemas"]["SyncReceipt"][];
      meta: components["schemas"]["EnvelopeMeta"];
    };
    SyncChange: {
      changeId: string;
      entityType: string;
      entityId: string;
      revision: number;
      /** Format: date-time */
      changedAt: string;
      payload: components["schemas"]["SyncPayload"];
    };
    SyncPullResponse: {
      data: components["schemas"]["SyncChange"][];
      meta: components["schemas"]["EnvelopeMeta"];
    };
    /** @description 离线同步负载，当前仅包含进度同步的已知字段（position、completed），其他 entityType 的负载结构待领域模型确认 */
    SyncPayload: {
      position?: number;
      completed?: boolean;
    };
  };
  responses: {
    /** @description 请求参数无效或格式错误 */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "INVALID_REQUEST",
         *         "message": "请求参数无效",
         *         "details": {},
         *         "requestId": "00000000-0000-0000-0000-000000000002"
         *       }
         *     }
         */
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Authentication required or invalid */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Authenticated but outside allowed resource scope */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Resource does not exist or is not visible in the current school scope */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description State or revision conflict */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Required dependency unavailable */
    ServiceUnavailable: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Rate limited */
    TooManyRequests: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description 服务端内部错误 */
    InternalServerError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: {
    /** @description 学校（租户）标识 */
    SchoolId: string;
    /** @description 分页返回数量上限 */
    Limit: number;
    /** @description 游标， opaque 字符串 */
    Cursor: string;
    /** @description 课程版本 ID */
    CourseVersionId: string;
    /** @description 任务 ID */
    AssignmentId: string;
    /** @description 学习活动 ID */
    ActivityId: string;
    /** @description 提交 ID */
    SubmissionId: string;
    /** @description 幂等键，与认证主体、路由和请求摘要绑定；重复请求返回首次业务结果，具体保留期限由服务端策略决定 */
    IdempotencyKey: string;
    /** @description 客户端持有的资源 revision，冲突时返回 409 */
    IfMatch: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getLiveness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Process is alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "data": {
           *         "status": "ok",
           *         "timestamp": "2026-07-09T09:00:00Z"
           *       },
           *       "meta": {
           *         "requestId": "00000000-0000-0000-0000-000000000001"
           *       }
           *     }
           */
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      500: components["responses"]["InternalServerError"];
    };
  };
  getReadiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Required dependencies are ready */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      503: components["responses"]["ServiceUnavailable"];
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "identifier": "teacher@example.edu",
         *       "password": "secure-placeholder"
         *     }
         */
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Authenticated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthSessionResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      429: components["responses"]["TooManyRequests"];
    };
  };
  refreshSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session refreshed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthSessionResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current identity and memberships */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUserResponse"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  listCourseVersions: {
    parameters: {
      query?: {
        /** @description 分页返回数量上限 */
        limit?: components["parameters"]["Limit"];
        /** @description 游标， opaque 字符串 */
        cursor?: components["parameters"]["Cursor"];
        status?: components["schemas"]["CourseVersionStatus"];
      };
      header?: never;
      path: {
        /** @description 学校（租户）标识 */
        schoolId: components["parameters"]["SchoolId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Course versions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseVersionListResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  createCourseDraft: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 学校（租户）标识 */
        schoolId: components["parameters"]["SchoolId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "title": "一年级语音入门",
         *       "description": "语音意识基础课程",
         *       "gradeBand": "一年级",
         *       "locale": "zh-CN"
         *     }
         */
        "application/json": components["schemas"]["CreateCourseDraftRequest"];
      };
    };
    responses: {
      /** @description Draft created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseVersionResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  publishCourseVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 学校（租户）标识 */
        schoolId: components["parameters"]["SchoolId"];
        /** @description 课程版本 ID */
        courseVersionId: components["parameters"]["CourseVersionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Published immutable version */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseVersionResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
    };
  };
  listClasses: {
    parameters: {
      query?: {
        /** @description 分页返回数量上限 */
        limit?: components["parameters"]["Limit"];
        /** @description 游标， opaque 字符串 */
        cursor?: components["parameters"]["Cursor"];
      };
      header?: never;
      path: {
        /** @description 学校（租户）标识 */
        schoolId: components["parameters"]["SchoolId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Classes in active school scope */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClassListResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  createAssignment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 学校（租户）标识 */
        schoolId: components["parameters"]["SchoolId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "classId": "11111111-1111-1111-1111-111111111111",
         *       "courseVersionId": "22222222-2222-2222-2222-222222222222",
         *       "title": "第一周语音练习",
         *       "startsAt": "2026-07-10T00:00:00Z",
         *       "dueAt": "2026-07-17T23:59:59Z",
         *       "offlineRequired": true
         *     }
         */
        "application/json": components["schemas"]["CreateAssignmentRequest"];
      };
    };
    responses: {
      /** @description Assignment created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssignmentResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
    };
  };
  openAssignment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 学校（租户）标识 */
        schoolId: components["parameters"]["SchoolId"];
        /** @description 任务 ID */
        assignmentId: components["parameters"]["AssignmentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Assignment opened */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssignmentResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
    };
  };
  getMyTodayTasks: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 学校（租户）标识 */
        schoolId: components["parameters"]["SchoolId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Student today tasks */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TodayTasksResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  saveActivityProgress: {
    parameters: {
      query?: never;
      header: {
        /** @description 客户端持有的资源 revision，冲突时返回 409 */
        "If-Match": components["parameters"]["IfMatch"];
      };
      path: {
        /** @description 学校（租户）标识 */
        schoolId: components["parameters"]["SchoolId"];
        /** @description 学习活动 ID */
        activityId: components["parameters"]["ActivityId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "position": 12,
         *       "completed": false,
         *       "clientUpdatedAt": "2026-07-09T08:30:00Z"
         *     }
         */
        "application/json": components["schemas"]["SaveProgressRequest"];
      };
    };
    responses: {
      /** @description Progress saved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgressResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      500: components["responses"]["InternalServerError"];
    };
  };
  submitAssignment: {
    parameters: {
      query?: never;
      header: {
        /** @description 幂等键，与认证主体、路由和请求摘要绑定；重复请求返回首次业务结果，具体保留期限由服务端策略决定 */
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        /** @description 学校（租户）标识 */
        schoolId: components["parameters"]["SchoolId"];
        /** @description 任务 ID */
        assignmentId: components["parameters"]["AssignmentId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "attemptNo": 1,
         *       "deviceId": "33333333-3333-3333-3333-333333333333",
         *       "answers": [
         *         {
         *           "activityId": "44444444-4444-4444-4444-444444444444",
         *           "kind": "TEXT",
         *           "value": "示范回答",
         *           "audioAssetId": null
         *         }
         *       ]
         *     }
         */
        "application/json": components["schemas"]["SubmitAssignmentRequest"];
      };
    };
    responses: {
      /** @description Submission accepted */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubmissionResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      500: components["responses"]["InternalServerError"];
    };
  };
  releaseFeedback: {
    parameters: {
      query?: never;
      header: {
        /** @description 客户端持有的资源 revision，冲突时返回 409 */
        "If-Match": components["parameters"]["IfMatch"];
      };
      path: {
        /** @description 学校（租户）标识 */
        schoolId: components["parameters"]["SchoolId"];
        /** @description 提交 ID */
        submissionId: components["parameters"]["SubmissionId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "decision": "ACCEPT",
         *       "comment": "发音清晰，继续加油",
         *       "score": 85
         *     }
         */
        "application/json": components["schemas"]["ReleaseFeedbackRequest"];
      };
    };
    responses: {
      /** @description Feedback released */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedbackResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      500: components["responses"]["InternalServerError"];
    };
  };
  pushSyncOperations: {
    parameters: {
      query?: never;
      header: {
        /** @description 幂等键，与认证主体、路由和请求摘要绑定；重复请求返回首次业务结果，具体保留期限由服务端策略决定 */
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        /** @description 学校（租户）标识 */
        schoolId: components["parameters"]["SchoolId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "deviceId": "55555555-5555-5555-5555-555555555555",
         *       "operations": [
         *         {
         *           "operationId": "66666666-6666-6666-6666-666666666666",
         *           "entityType": "progress",
         *           "entityId": "77777777-7777-7777-7777-777777777777",
         *           "action": "upsert",
         *           "baseRevision": 3,
         *           "payload": {
         *             "position": 12,
         *             "completed": false
         *           },
         *           "createdAt": "2026-07-09T08:30:00Z"
         *         }
         *       ]
         *     }
         */
        "application/json": components["schemas"]["SyncPushRequest"];
      };
    };
    responses: {
      /** @description Per-operation receipts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SyncPushResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      500: components["responses"]["InternalServerError"];
    };
  };
  pullSyncChanges: {
    parameters: {
      query?: {
        cursor?: string;
      };
      header?: never;
      path: {
        /** @description 学校（租户）标识 */
        schoolId: components["parameters"]["SchoolId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Changes since cursor */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SyncPullResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      500: components["responses"]["InternalServerError"];
    };
  };
}
