(() => {
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  const toast = $('.toast');
  const modal = $('#modal');
  const modalTitle = $('#modal-title');
  const modalCopy = $('#modal-copy');
  let toastTimer;
  const showToast = (text) => {
    toast.textContent = text; toast.classList.add('show');
    clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 1900);
  };
  const openModal = (title, copy) => {
    modalTitle.textContent = title; modalCopy.textContent = copy;
    if (typeof modal.showModal === 'function') modal.showModal(); else modal.setAttribute('open','');
    $('.scrim').classList.add('show');
  };
  const closeModal = () => {
    if (modal.open && typeof modal.close === 'function') modal.close(); else modal.removeAttribute('open');
    $('.scrim').classList.remove('show');
    $('.right-rail').classList.remove('open');
  };
  $$('[data-close-modal]').forEach(el => el.addEventListener('click', closeModal));

  // Waveform generated by code so it can reflect real playback state.
  const wave = $('.waveform');
  const heights = [8,12,17,10,22,14,9,18,25,12,8,20,14,23,11,17,26,13,8,18,24,15,9,20,12,27,16,10,22,14,9,18,25,11,7,19,14,23,12,17,26,13,8,20,24,15,9,18,12,25,16,10,21,14,8,18,23,11,7,17,13,21,12,16,24,12,8,18,22,14,9,17,12,20];
  heights.forEach(h => { const i=document.createElement('i'); i.style.height=`${h}px`; wave.appendChild(i); });

  let playing = false, elapsed = 0, duration = 138, timer;
  const syncPlayback = () => {
    document.body.classList.toggle('playing', playing);
    const bars = $$('.waveform i');
    const count = Math.round((elapsed/duration)*bars.length);
    bars.forEach((b,i)=>b.classList.toggle('played',i<count));
    const remain = Math.max(0,duration-elapsed), m=Math.floor(remain/60), s=remain%60;
    $('#audio-time').textContent = `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;
  };
  const togglePlay = () => {
    playing=!playing; clearInterval(timer);
    if(playing){
      timer=setInterval(()=>{ elapsed=(elapsed+1)%duration; syncPlayback(); },1000);
      showToast('正在播放本周精选作品');
    }
    syncPlayback();
  };
  $$('[data-play]').forEach(b=>b.addEventListener('click',togglePlay));

  const applyTheme = (button) => {
    const name=button.dataset.theme, title=button.dataset.title;
    $$('.theme-tab,.theme-card').forEach(b=>b.classList.toggle('active',b.dataset.theme===name));
    $('#featured-title').textContent=title;
    $('#featured-theme').textContent=name;
    showToast(`已切换至“${name}”主题`);
  };
  $$('.theme-tab,.theme-card').forEach(b=>b.addEventListener('click',()=>applyTheme(b)));
  $$('[data-nav]').forEach(b=>b.addEventListener('click',()=>{$$('[data-nav]').forEach(x=>x.classList.remove('active'));b.classList.add('active');showToast(`${b.textContent.trim()}模块演示`)}));
  $$('[data-side]').forEach(b=>b.addEventListener('click',()=>{$$('[data-side]').forEach(x=>x.classList.remove('active'));b.classList.add('active');showToast(`${b.textContent.trim()}页面演示`)}));

  const messages = {
    about:['关于声音河谷','这里展示经过教师审核的朗诵、故事与文化交流作品。未审核内容只对作者和教师可见。'],
    offline:['离线管理','你可以提前下载课程与作品。离线状态下，提交和教师反馈会在恢复网络后同步。'],
    profile:['学生账户','当前为学生演示账户。真实姓名、学校、年级和权限应由业务接口返回。'],
    more:['更多精选作品','作品列表将按审核状态、主题和班级权限加载，不会展示未通过审核的内容。'],
    'all-themes':['全部主题','完整主题页支持筛选、报名状态、开始时间和无障碍浏览。'],
    'choose-theme':['选择主题','请选择正在进行的主题，阅读要求后再开始准备作品。'],
    submit:['提交作品','录音、视频与文字说明将在提交前进行隐私提示，并由教师审核。'],
    review:['教师评审','待审核作品只对作者和教师可见，评审意见会保留修改记录。'],
    growth:['收获成长','通过作品积累教师反馈与学习记录，不使用夸张游戏化排名。'],
    status:['作品状态','状态同时通过文字、图标和边界呈现，不仅依赖颜色。'],
    'all-submissions':['我的全部作品','可查看草稿、待评审、已通过和退回修改的作品。'],
    feedback:['教师反馈','新反馈包含节奏、发音与表达建议。确认阅读后可进入作品修改。'],
    rules:['社区公约','尊重他人、保护隐私、坚持原创。违规内容可举报并进入教师审核流程。'],
    'content-review':['内容审核','作品发布前必须经过教师审核，敏感信息将被提醒或拦截。'],
    privacy:['隐私保护','未成年人信息默认最小化展示，真实数据受租户和角色权限控制。'],
    report:['举报与校园投诉','举报内容会进入受限处理流程，并保留必要的审计记录。'],
    parent:['家长控制设置','家长可管理公开范围、通知与可参与主题，具体能力取决于真实授权。'],
    agreement:['用户协议','协议内容应由正式运营版本提供。'],
    help:['帮助中心','这里将接入常见问题、教师联系人与离线使用说明。'],
    'feedback-general':['反馈建议','可提交产品建议，但不得上传包含他人隐私的材料。']
  };
  $$('[data-action]').forEach(b=>b.addEventListener('click',()=>{
    const action=b.dataset.action;
    if(action==='mobile-rail'){$('.right-rail').classList.add('open');$('.scrim').classList.add('show');return;}
    const item=messages[action]||['功能演示','这是高保真静态交互演示，后续可接入真实业务数据。'];openModal(item[0],item[1]);
  }));

  // Close mobile information drawer with Escape.
  document.addEventListener('keydown',e=>{ if(e.key==='Escape') closeModal(); });
  syncPlayback();
})();
