(()=>{
'use strict';
const homeEmbed=document.querySelector('#home-plans-embed');
const qaMode=new URLSearchParams(location.search).get('qa')==='1';
const embedMode=new URLSearchParams(location.search).get('embed')==='1' || !!homeEmbed;
const app=homeEmbed || document.querySelector('#plans-app');
let modalRoot=document.querySelector('#plans-modal');
let toastRoot=document.querySelector('#plans-toast');
if(homeEmbed){
  if(!modalRoot){
    modalRoot=document.createElement('div');
    modalRoot.id='plans-modal';
    document.body.appendChild(modalRoot);
  }
  if(!toastRoot){
    toastRoot=document.createElement('div');
    toastRoot.id='plans-toast';
    toastRoot.className='plans-toast-root';
    toastRoot.setAttribute('aria-live','polite');
    document.body.appendChild(toastRoot);
  }
}
const clone=o=>JSON.parse(JSON.stringify(o));
const merge=(a,b)=>{if(Array.isArray(b))return clone(b);if(!b||typeof b!=='object')return b;const out={...a};for(const [k,v] of Object.entries(b))out[k]=v&&typeof v==='object'&&!Array.isArray(v)?merge(a?.[k]||{},v):clone(v);return out};
const icons={
 user:`<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3.5" fill="none" stroke="currentColor" stroke-width="1.7"/><path d="M5 20c.7-4.2 3-6.4 7-6.4s6.3 2.2 7 6.4" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>`,
 school:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 10 9-7 9 7v11H3Z" fill="none" stroke="currentColor" stroke-width="1.7"/><path d="M8 21v-7h8v7M7 10h10" fill="none" stroke="currentColor" stroke-width="1.7"/></svg>`,
 building:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 21V5h10v16M15 10h4v11M8 8h4M8 12h4M8 16h4" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>`,
 group:`<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="8" r="3" fill="none" stroke="currentColor" stroke-width="1.7"/><circle cx="17" cy="10" r="2.3" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M3 20c.6-4.3 2.6-6.4 6-6.4 3.5 0 5.5 2.1 6 6.4M15 15c3.2-.2 5.1 1.4 5.7 4.8" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>`,
 book:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 5.5c3.7-.8 6.7-.1 9 2v12c-2.3-2.1-5.3-2.8-9-2Zm18 0c-3.7-.8-6.7-.1-9 2v12c2.3-2.1 5.3-2.8 9-2Z" fill="none" stroke="currentColor" stroke-width="1.6"/></svg>`,
 chart:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20V9m5 11V4m5 16v-7m5 7V7M2 20h20" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg>`,
 teacher:`<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="8" cy="7" r="3" fill="none" stroke="currentColor" stroke-width="1.6"/><path d="M3 20c.7-4 2.3-6 5-6s4.3 2 5 6M14 5h7v9h-5M14 10l3-2" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg>`,
 report:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 3h11l3 3v15H5Z" fill="none" stroke="currentColor" stroke-width="1.6"/><path d="M16 3v4h4M8 11h8M8 15h8M8 19h5" fill="none" stroke="currentColor" stroke-width="1.6"/></svg>`,
 activity:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20V7l8-4 8 4v13ZM4 9h16M9 20v-6h6v6" fill="none" stroke="currentColor" stroke-width="1.6"/></svg>`,
 heart:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 20S4 15.4 4 9.2C4 6.3 6 4.5 8.6 4.5c1.5 0 2.7.8 3.4 2 1-1.2 2.1-2 3.7-2C18.2 4.5 20 6.3 20 9c0 6.2-8 11-8 11Z" fill="none" stroke="currentColor" stroke-width="1.7"/></svg>`,
 location:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21s7-6.1 7-12a7 7 0 1 0-14 0c0 5.9 7 12 7 12Z" fill="none" stroke="currentColor" stroke-width="1.7"/><circle cx="12" cy="9" r="2.5" fill="none" stroke="currentColor" stroke-width="1.7"/></svg>`,
 check:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4 10-10" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
 arrow:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>`
};
const defaults={
 viewer:{role:'guest',loggedIn:false},
 nav:[['/', '首页'],['/student/courses','学习路径'],['/plans','产品套餐'],['/teacher','教师资源'],['/volunteer','公益与志愿'],['/about','关于我们']],
 schoolTypes:[
  {id:'rural',label:'乡村小学\n薄弱学校',icon:'school',plan:'inclusive'},
  {id:'county',label:'县域中学\n城镇学校',icon:'building',plan:'professional'},
  {id:'group',label:'示范校\n教育集团',icon:'group',plan:'flagship'}
 ],
 selectedSchoolType:'rural',selectedPlan:'inclusive',discount:.8,
 plans:[
  {id:'inclusive',name:'普惠版 · 基础支持',price:'免费',priceSuffix:'',audience:'面向乡村小学 / 薄弱学校',description:'提供基础工具与资源，让每一所学校都能迈出提升的第一步。',status:'normal',nodes:[['book','基础测评'],['chart','资源支持'],['group','教师社群'],['heart','持续陪伴']]},
  {id:'professional',name:'专业版 · 能力提升',price:'2–4',priceSuffix:'万元/校/学年',audience:'面向县域中学 / 城镇学校',description:'系统化能力提升，帮助学校建立可持续的教学改进机制。',status:'normal',nodes:[['chart','学情诊断'],['teacher','教师培训'],['report','学情报告'],['activity','练习反馈']]},
  {id:'flagship',name:'旗舰版 · 深度共建',price:'5–8',priceSuffix:'万元/校/学年',audience:'面向示范校 / 教育集团',description:'深度共建，推动学校整体发展与教育生态协同进步。',status:'pending',nodes:[['book','定制课程'],['teacher','跟岗培训'],['location','文化交流'],['heart','心理适应']]}
 ],
 services:[
  ['智能测评与学情分析',1,1,1],['优质教学资源支持','基础版','标准版','增强版'],['教师培训与成长','—','线上 + 线下','线下研修 + 跟岗'],['学情报告与反馈','—',1,1],['定制化课程开发','—',1,1],['跟岗培训与名校研修','—',1,1],['学生文化交流活动','—','—',1],['心理适应与成长支持','—',1,1],['专属顾问与长期陪伴','社群支持','专属顾问','专属顾问 + 年度评估']
 ],
 consultation:{region:'',schoolType:'',name:'',phone:'',status:'idle',message:''},
 ui:{pageState:'normal',modal:null,compareExpanded:true},
 permissions:{consult:true,trial:true}
};
let state=merge(defaults,window.__YUZAN_PLANS_BOOTSTRAP__||{});
function planForSchool(id){return state.schoolTypes.find(x=>x.id===id)?.plan||'inclusive'}
function route(path){if(path==='/plans'){if(location.origin!=='null')history.pushState({},'',path+(qaMode?'?qa=1':''));render();return}if(embedMode){if(window.top&&window.top!==window){window.top.location.href=path;return}}toast('该公共页面已进入后续逐页开发队列。')}
function render(){if(!homeEmbed)document.title='语赞心声｜产品套餐';if(state.ui.pageState==='loading')return renderPageState('正在加载套餐配置','正在读取地区、学校类型与合作服务。',true);if(state.ui.pageState==='error')return renderPageState('套餐配置暂不可用','请稍后重试，或直接提交咨询需求。',false);app.innerHTML=`<div class="plans-page${embedMode?' embed':''}">${embedMode?'':header()}<main class="plans-wrap">${title()}<div class="workspace">${schoolFilter()}<section>${planStage()}${compare()}</section>${rightRail()}</div>${bottomCta()}</main></div>`;bind();renderModal()}
function header(){return `<header class="public-header"><nav class="public-nav" aria-label="主导航">${state.nav.map(([p,l])=>`<a href="${p}" data-route="${p}" class="${p==='/plans'?'active':''}">${l}</a>`).join('')}</nav><div class="header-actions"><button class="btn btn-outline" id="login-workbench">${icons.user}登录教师工作台</button><button class="btn btn-primary" data-trial>申请试用</button></div></header>`}
function title(){return `<section class="plans-title"><h1>为不同学校，匹配合适的<em>援藏教育方案</em></h1><p>三条服务路径，覆盖从基础支持到深度共建，陪伴学校与教师持续成长。</p></section>`}
function schoolFilter(){return `<aside class="school-filter panel"><h2>选择学校类型</h2><p>选择后查看推荐路径</p><div class="school-type-wrap">${state.schoolTypes.map(s=>`<button class="school-type ${state.selectedSchoolType===s.id?'active':''}" data-school-type="${s.id}">${icons[s.icon]}<span>${s.label.replace('\n','<br>')}</span></button>`).join('')}</div><div class="filter-help">不知道如何选择？<br><button id="contact-advisor">联系我们的顾问</button></div></aside>`}
function planStage(){return `<section class="plan-stage panel"><div class="plan-paths">${state.plans.map(planColumn).join('')}</div></section>`}
function planColumn(p){const focused=state.selectedPlan===p.id,dim=state.selectedPlan&& !focused;let status='';if(p.status==='pending')status='<span class="plan-state pending">地区方案待确认</span>';if(p.status==='missing')status='<span class="plan-state missing">价格配置缺失</span>';return `<article class="plan-column ${focused?'focused':''} ${dim?'dimmed':''}" data-plan="${p.id}">${status}<div class="plan-label">${p.name}</div><div class="plan-price">${p.status==='missing'?'待配置':p.price} ${p.priceSuffix?`<small>${p.priceSuffix}</small>`:''}</div><div class="plan-audience">${p.audience}</div><div class="path-track"><div class="path-line"></div><div class="path-nodes">${p.nodes.map(([ic,l])=>`<div class="path-node"><i>${icons[ic]}</i><span>${l}</span></div>`).join('')}</div></div><div class="plan-description">${p.description}</div></article>`}
function mark(v,cls){if(v===1)return `<span class="mark ${cls}">✓</span>`;if(v==='—')return `<span class="dash">—</span>`;return v}
function compare(){const cls=['','green','gold','red'];return `<div class="compare-wrap"><section class="compare-panel panel"><div class="compare-head">服务差异对比 <button id="toggle-compare">${state.ui.compareExpanded?'收起':'展开'}</button></div>${state.ui.compareExpanded?`<table class="comparison"><thead><tr><th>服务内容</th><th>普惠版 · 基础支持<br><small>免费</small></th><th>专业版 · 能力提升<br><small>2–4 万元/校/学年</small></th><th>旗舰版 · 深度共建<br><small>5–8 万元/校/学年</small></th></tr></thead><tbody>${state.services.map(row=>`<tr>${row.map((v,i)=>`<td>${i?mark(v,cls[i]):v}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="compare-note">* 具体服务内容可根据学校实际需求进行调整，详情请咨询我们的教育顾问。</div>`:''}</section><section class="status-panel panel"><h3>状态说明</h3><div class="status-item normal"><i></i><span><strong>正常展示</strong><small>服务信息完整，可直接选择方案</small></span></div><div class="status-item missing"><i></i><span><strong>价格配置缺失</strong><small>当前价格未配置，请联系顾问</small></span></div><div class="status-item pending"><i></i><span><strong>地区方案待确认</strong><small>地区折扣需确认后生效</small></span></div><div class="status-item sent"><i></i><span><strong>咨询已提交</strong><small>顾问将在 1 个工作日内联系</small></span></div></section></div>`}
function rightRail(){const c=state.consultation;return `<aside class="right-rail"><section class="consult-card panel"><h2>咨询方案</h2><p>我们的教育顾问将为您定制方案</p><form id="consult-form" novalidate><label class="form-field"><span>所在地区</span><select name="region"><option value="">请选择地区</option><option ${c.region==='西藏自治区'?'selected':''}>西藏自治区</option><option ${c.region==='青海省'?'selected':''}>青海省</option><option ${c.region==='四川省'?'selected':''}>四川省</option></select></label><label class="form-field"><span>学校类型</span><select name="schoolType"><option value="">请选择学校类型</option>${state.schoolTypes.map(x=>`<option value="${x.id}" ${c.schoolType===x.id?'selected':''}>${x.label.replace('\n',' / ')}</option>`).join('')}</select></label><label class="form-field"><span>您的姓名</span><input name="name" value="${escapeHtml(c.name)}" placeholder="请输入姓名" autocomplete="name"></label><label class="form-field"><span>联系电话</span><input name="phone" value="${escapeHtml(c.phone)}" placeholder="请输入手机号码" inputmode="tel" autocomplete="tel"></label><div class="form-error">${c.message||''}</div><button class="consult-submit" ${c.status==='submitting'?'disabled':''}>${c.status==='submitting'?'提交中…':'提交咨询'}</button><div class="submit-state ${c.status==='failed'?'error':''}">${c.status==='submitted'?`${icons.check} 提交成功`:c.status==='failed'?'提交失败，请重试':''}</div></form></section><section class="info-card panel"><h3>地区折扣说明</h3><div class="discount-row"><span class="discount-value">${state.discount.toFixed(1)} – 1.0</span><span class="discount-badge">地区折扣系数</span></div><button class="discount-selector" id="discount-select" aria-label="调整地区折扣系数"><span>当前预估 ${state.discount.toFixed(1)}</span><small>调整</small></button><p>根据地区经济发展水平确定具体折扣。</p><button class="text-link" id="discount-detail">查看折扣细则 →</button></section><section class="info-card panel"><h3>资金来源说明</h3><ul class="funding-list"><li>政府专项支持</li><li>企业 / 社会组织捐赠</li><li>爱心机构合作共建</li><li>志愿者与专家公益支持</li></ul><button class="text-link" id="funding-detail">了解更多资金使用原则 →</button></section></aside>`}
function bottomCta(){return `<section class="bottom-cta"><span class="cta-icon">${icons.heart}</span><span class="cta-copy"><strong>让每一次发声，沿着高原的学习路径被听见</strong><small>从能力诊断出发，连接课程、教师支持、练习反馈与持续复测。</small></span><button class="btn btn-outline" id="cases-btn">查看合作案例</button><button class="btn btn-primary" data-trial>申请试用</button></section>`}
function bind(){document.querySelectorAll('[data-route]').forEach(x=>x.onclick=e=>{e.preventDefault();route(x.dataset.route)});document.querySelectorAll('[data-school-type]').forEach(x=>x.onclick=()=>selectSchool(x.dataset.schoolType));document.querySelectorAll('[data-plan]').forEach(x=>x.onclick=()=>{state.selectedPlan=x.dataset.plan;render();toast(`已选择${state.plans.find(p=>p.id===state.selectedPlan)?.name}。`,'success')});document.querySelectorAll('[data-trial]').forEach(x=>x.onclick=openTrial);document.querySelector('#login-workbench')?.addEventListener('click',()=>route('/teacher'));document.querySelector('#contact-advisor')?.addEventListener('click',focusConsult);document.querySelector('#toggle-compare')?.addEventListener('click',()=>{state.ui.compareExpanded=!state.ui.compareExpanded;render()});document.querySelector('#consult-form')?.addEventListener('submit',submitConsult);document.querySelector('#discount-select')?.addEventListener('click',openDiscountSelector);document.querySelector('#discount-detail')?.addEventListener('click',()=>openModal('地区折扣说明',`地区折扣系数根据学校所在地、项目资金来源和合作规模综合确认。当前选择 ${state.discount.toFixed(1)} 仅用于方案预估，不构成正式报价。`));document.querySelector('#funding-detail')?.addEventListener('click',()=>openModal('资金使用原则','公益资金优先用于薄弱学校基础支持、教师培训和学生学习资源。所有合作以正式协议、项目预算和审计要求为准。'));document.querySelector('#cases-btn')?.addEventListener('click',()=>openModal('合作案例','合作案例页正在逐页还原队列中。当前页面仅展示套餐选择与咨询闭环。'))}
function selectSchool(id){state.selectedSchoolType=id;state.selectedPlan=planForSchool(id);state.consultation.schoolType=id;render();toast(`已为${state.schoolTypes.find(x=>x.id===id)?.label.replace('\n','')}高亮推荐方案。`,'success')}
function focusConsult(){document.querySelector('.consult-card')?.scrollIntoView({behavior:qaMode?'auto':'smooth',block:'center'});setTimeout(()=>document.querySelector('[name="region"]')?.focus(),qaMode?0:350)}
function submitConsult(e){e.preventDefault();if(!state.permissions.consult)return toast('当前模式不允许提交咨询。','error');const fd=new FormData(e.currentTarget),values=Object.fromEntries(fd.entries());state.consultation={...state.consultation,...values,message:'',status:'idle'};if(!values.region||!values.schoolType||!values.name.trim()){state.consultation.message='请完整填写地区、学校类型和姓名。';render();return}if(!/^1\d{10}$/.test(values.phone)){state.consultation.message='请输入有效的 11 位手机号码。';render();return}state.consultation.status='submitting';render();try{const drafts=JSON.parse(localStorage.getItem('yuzan-consult-drafts')||'[]');drafts.push({...values,savedAt:new Date().toISOString()});localStorage.setItem('yuzan-consult-drafts',JSON.stringify(drafts));state.consultation.status='submitted_local';state.consultation.message='咨询信息已保存到本机草稿。在线提交接口暂未开通，请直接致电 400-000-0000 或邮件至 contact@example.com，我们的顾问会在 1 个工作日内联系您。';render();toast('咨询草稿已保存到本机，请联系顾问完成正式提交。','success')}catch(err){state.consultation.status='failed';state.consultation.message='本地保存失败：'+(err&&err.message||'未知错误');render();toast('提交失败，请直接致电 400-000-0000 联系顾问。','error')}}
function openDiscountSelector(){openForm('地区折扣预估',`<p style="margin-top:0;color:#666">拖动系数仅用于方案预估，最终折扣需由项目顾问确认。</p><input id="discount-modal-range" type="range" min="0.6" max="1" step="0.1" value="${state.discount}" style="width:100%;accent-color:#bb7710"><div id="discount-modal-value" style="font:700 28px Georgia;text-align:center;color:#9d5912;margin-top:12px">${state.discount.toFixed(1)}</div>`,()=>{state.discount=+document.querySelector('#discount-modal-range').value;closeModal();render();toast('地区折扣预估已更新，正式方案仍需人工确认。','success')});setTimeout(()=>{const r=document.querySelector('#discount-modal-range'),v=document.querySelector('#discount-modal-value');if(r)r.oninput=()=>v.textContent=(+r.value).toFixed(1)},0)}
function openTrial(){if(!state.permissions.trial)return toast('当前模式不允许申请试用。','error');openForm('申请试用',`<label class="form-field"><span>学校名称</span><input id="trial-school" placeholder="请输入学校名称"></label><label class="form-field"><span>联系人</span><input id="trial-contact" placeholder="请输入联系人"></label><label class="form-field"><span>联系电话</span><input id="trial-phone" inputmode="tel" placeholder="请输入手机号码"></label><p style="color:#777;font-size:12px">提交后进入人工需求确认，不会自动开通或生成虚假成功状态。</p>`,()=>{const school=document.querySelector('#trial-school').value.trim(),contact=document.querySelector('#trial-contact').value.trim(),phone=document.querySelector('#trial-phone').value.trim();if(!school||!contact||!/^1\d{10}$/.test(phone))return toast('请完整填写有效的试用申请信息。','error');try{const drafts=JSON.parse(localStorage.getItem('yuzan-trial-drafts')||'[]');drafts.push({school,contact,phone,savedAt:new Date().toISOString()});localStorage.setItem('yuzan-trial-drafts',JSON.stringify(drafts));closeModal();toast('试用申请已保存到本机草稿，请致电 400-000-0000 完成正式申请。','success')}catch(err){toast('本地保存失败，请直接致电 400-000-0000 申请试用。','error')}})}
function openModal(title,body){state.ui.modal={title,body,type:'info'};renderModal()}function openForm(title,body,onConfirm){state.ui.modal={title,body,type:'form',onConfirm};renderModal()}
function renderModal(){const m=state.ui.modal;if(!m){modalRoot.innerHTML='';return}modalRoot.innerHTML=`<div class="plans-modal-backdrop"><section class="plans-modal" role="dialog" aria-modal="true" aria-labelledby="plans-modal-title"><div class="plans-modal-head"><strong id="plans-modal-title">${m.title}</strong><button id="plans-modal-close" aria-label="关闭">×</button></div><div class="plans-modal-body">${m.type==='form'?m.body:`<p style="margin:0">${m.body}</p>`}</div><div class="plans-modal-actions"><button class="btn btn-secondary" id="plans-modal-cancel">取消</button><button class="btn btn-primary" id="plans-modal-confirm">${m.type==='form'?'提交':'知道了'}</button></div></section></div>`;document.querySelector('#plans-modal-close').onclick=closeModal;document.querySelector('#plans-modal-cancel').onclick=closeModal;document.querySelector('#plans-modal-confirm').onclick=m.type==='form'?m.onConfirm:closeModal;document.querySelector('.plans-modal-backdrop').onclick=e=>{if(e.target===e.currentTarget)closeModal()}}
function closeModal(){state.ui.modal=null;renderModal()}function toast(message,type=''){const el=document.createElement('div');el.className=`plans-toast ${type}`;el.textContent=message;toastRoot.append(el);setTimeout(()=>el.remove(),qaMode?650:2800)}
function renderPageState(title,text,loading){app.innerHTML=`<div class="plans-page${embedMode?' embed':''}">${embedMode?'':header()}<main class="page-state"><div>${loading?'<div class="loading-dot">●</div>':icons.school}<h2>${title}</h2><p>${text}</p>${loading?'':'<button class="btn btn-primary" id="plans-retry">重新加载</button>'}</div></main></div>`;document.querySelector('#plans-retry')?.addEventListener('click',()=>{state.ui.pageState='loading';render();try{location.reload()}catch(_){state.ui.pageState='error';render();toast('刷新失败，请手动按 F5 重载页面。','error')}});bindHeaderOnly()}
function bindHeaderOnly(){document.querySelectorAll('[data-route]').forEach(x=>x.onclick=e=>{e.preventDefault();route(x.dataset.route)});document.querySelectorAll('[data-trial]').forEach(x=>x.onclick=openTrial);document.querySelector('#login-workbench')?.addEventListener('click',()=>route('/teacher'))}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});window.addEventListener('popstate',render);
window.YuzanPlans={hydrate(next){state=merge(state,next);render()},getState(){return clone(state)},async loadBackendState(url){state.ui.pageState='loading';render();try{const r=await fetch(url);if(!r.ok)throw new Error(`HTTP ${r.status}`);state=merge(state,await r.json());state.ui.pageState='normal';render()}catch(e){state.ui.pageState='error';render();throw e}},setDemoState(name){if(name==='missing-price'){state.plans[1].status='missing'}if(name==='pending-region'){state.plans[2].status='pending'}if(name==='submit-failed'){state.ui.forceSubmitFailure=true}if(name==='empty'){state.plans=[];state.services=[]}render()}};
render();
})();
