(()=>{
'use strict';
const qaMode=new URLSearchParams(location.search).get('qa')==='1';
const app=document.querySelector('#research-app'),modalRoot=document.querySelector('#research-modal'),toastRoot=document.querySelector('#research-toast');
const clone=o=>JSON.parse(JSON.stringify(o));
const merge=(a,b)=>{if(Array.isArray(b))return clone(b);if(!b||typeof b!=='object')return b;const out={...a};for(const[k,v]of Object.entries(b))out[k]=v&&typeof v==='object'&&!Array.isArray(v)?merge(a?.[k]||{},v):clone(v);return out};
const icon=(name)=>{const paths={home:'<path d="M3 11 12 4l9 7v9H3Z M8 20v-6h8v6"/>',research:'<circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/>',book:'<path d="M4 5c3.5-.8 6.2-.1 8 2v12c-1.8-2.1-4.5-2.8-8-2Zm16 0c-3.5-.8-6.2-.1-8 2v12c1.8-2.1 4.5-2.8 8-2Z"/>',test:'<path d="M6 3h12v18H6Z M9 8h6M9 12h6M9 16h4"/>',folder:'<path d="M3 7h7l2-2h9v14H3Z"/>',link:'<path d="M9 15 7 17a4 4 0 0 1-6-6l3-3a4 4 0 0 1 6 0M15 9l2-2a4 4 0 0 1 6 6l-3 3a4 4 0 0 1-6 0M8 12h8"/>',teacher:'<circle cx="9" cy="7" r="3"/><path d="M3 20c.8-4 2.8-6 6-6s5.2 2 6 6M15 6h6v8h-5"/>',data:'<circle cx="12" cy="12" r="9"/><path d="M8 15v-3m4 3V8m4 7v-5"/>',chart:'<path d="M4 20V4m0 16h16M8 16l3-4 3 2 5-7"/>',history:'<path d="M4 5v5h5M5 10a8 8 0 1 1 2 7M12 7v5l3 2"/>',gear:'<circle cx="12" cy="12" r="3"/><path d="m12 2 1 3 3 1 3-1 2 3-2 2 1 3 2 2-2 3-3-1-3 1-1 3H9l-1-3-3-1-3 1-2-3 2-2-1-3-2-2 2-3 3 1 3-1 1-3Z"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M3 20c.7-4 2.7-6 6-6s5.3 2 6 6M16 7a2.5 2.5 0 0 1 0 5m0 3c3 0 4.5 1.7 5 5"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',bell:'<path d="M6 17h12l-2-3V9a4 4 0 0 0-8 0v5Zm4 3h4"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.6 2.6 0 1 1 3.5 2.5c-1 .4-1 1.1-1 2M12 17h.01"/>',brain:'<path d="M9 4a3 3 0 0 0-5 2 3 3 0 0 0 0 5 3 3 0 0 0 2 5 3 3 0 0 0 5 2V6a2 2 0 0 0-2-2Zm6 0a3 3 0 0 1 5 2 3 3 0 0 1 0 5 3 3 0 0 1-2 5 3 3 0 0 1-5 2V6a2 2 0 0 1 2-2Z"/>',graph:'<circle cx="5" cy="12" r="3"/><circle cx="18" cy="5" r="3"/><circle cx="19" cy="19" r="3"/><path d="m8 11 7-4m-7 7 8 4"/>',resource:'<path d="M5 3h11l3 3v15H5Z M16 3v4h4 M8 11h8M8 15h6"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${paths[name]||paths.resource}</svg>`};
const defaults={
 viewer:{name:'王老师',role:'教研员'},
 permissions:{review:true,publish:true,managePlatform:false},
 activeSpace:'research',activeTab:'versions',activeStage:3,selectedStatus:'all',
 stages:[['问题发现','来自课堂与测评'],['证据收集','数据与课证据'],['方案设计','形成改进方案'],['试用验证','小范围试用'],['评审优化','专家评审与优化'],['发布计划','纳入课程计划']],
 counts:[['进行中',3],['待评审',5],['试用中',2],['即将发布',1],['已发布',8],['已归档',12]],
 topic:{id:'RES-2024-028',title:'小学高年级朗读策略优化研究',status:'进行中',stage:'方案设计（第 3 步 / 共 6 步）',grade:'小学 / 语文',owner:'王老师',members:7,created:'2024-03-12',progress:55},
 versions:[
  {name:'小学语文五年级上册 · 朗读单元优化版',version:'v1.3.0',status:'使用中',stage:'试用验证',editor:'李老师',updated:'2024-05-21 10:24'},
  {name:'小学语文五年级上册 · 朗读单元优化版',version:'v1.2.0',status:'试用中',stage:'方案设计',editor:'张老师',updated:'2024-05-10 16:40'},
  {name:'小学语文五年级上册 · 朗读单元优化版',version:'v1.1.0',status:'待评审',stage:'评审优化',editor:'李老师',updated:'2024-04-28 09:15'},
  {name:'小学语文五年级上册 · 朗读单元优化版',version:'v1.0.0',status:'已归档',stage:'问题发现',editor:'王老师',updated:'2024-04-12 14:33'}
 ],
 resources:[['教学设计',24,6,'book'],['课件',18,3,'chart'],['学习单',36,9,'resource'],['音频',52,11,'data'],['视频',27,4,'test'],['文本材料',41,7,'resource']],
 feedback:[
  {teacher:'扎西老师',tag:'课堂反馈',text:'在朗读表现评价中，学生对情感表达的自评维度理解有偏差…',source:'拉萨市堆龙德庆区第二小学',time:'05-20 16:42',version:'v1.3.0'},
  {teacher:'次仁老师',tag:'资源建议',text:'建议补充更多贴近城区生活的朗读材料，增强学生共鸣。',source:'日喀则市桑珠孜区第一小学',time:'05-19 11:28',version:'v1.2.0'},
  {teacher:'央金老师',tag:'试用反馈',text:'新版中的朗读策略对学生的停顿把握有显著帮助，但部分…',source:'昌都市卡若区实验小学',time:'05-18 09:35',version:'v1.3.0'}
 ],
 ui:{pageState:'normal',modal:null,search:'',noActiveTopic:false,dataInsufficient:true,reviewBacklog:false}
};
let state=merge(defaults,window.__YUZAN_RESEARCH_BOOTSTRAP__||{});
const navGroups=[
 ['工作台','home',[]],['教研与内容','research',[['教研中心','/research'],['课程版本','/research/versions'],['测评内容','/research/assessments'],['资源库','/resources'],['引用与关联','/research/links']]],['教学与支持','teacher',[['课堂教学','/research/teaching'],['教师反馈','/research/feedback'],['评审任务','/research/reviews']]],['数据与洞察','data',[['数据洞察','/research/insights'],['指标看板','/research/metrics'],['数据回溯','/research/history']]],['平台管理','gear',[['组织与权限','/admin/users-roles'],['系统设置','/admin/settings']]]
];
function render(){if(state.ui.pageState==='loading')return pageState('正在加载教研空间','正在同步课题、版本与教师反馈。',true);if(state.ui.pageState==='error')return pageState('教研数据暂不可用','已保留当前筛选，请稍后重试。',false);app.innerHTML=`<div class="r-shell">${sidebar()}${header()}<main class="r-main"><section class="r-primary">${researchPath()}${association()}${resources()}${insights()}</section><aside class="r-rail">${activeTopic()}${pending()}${feedback()}${mindTools()}</aside></main></div>`;bind();renderModal()}
function sidebar(){return `<aside class="r-sidebar"><nav class="r-nav">${navGroups.map(([title,ic,subs])=>`<section class="r-nav-group"><button class="r-nav-main ${title==='教研与内容'?'active':''}">${icon(ic)}<strong>${title}</strong>${subs.length?'<span>⌃</span>':''}</button>${subs.length?`<div class="r-nav-sub">${subs.map(([l,p])=>`<button data-route="${p}" class="${p==='/research'?'active':''}">${l}</button>`).join('')}</div>`:''}</section>`).join('')}</nav><button class="sidebar-cta" id="brand-story">${icon('research')}<span>援藏教育<br>让每一次教学被看见</span></button></aside>`}
function header(){return `<header class="r-header"><div class="r-header-top"><div class="r-title"><h1>教研中心</h1><p>围绕真实课堂问题，形成可验证、可复用、可迭代的内容改进路径</p></div><label class="r-search">${icon('search')}<input id="global-search" value="${escapeHtml(state.ui.search)}" placeholder="全局搜索（课题/版本/资源/反馈）"><kbd>Ctrl K</kbd></label><button class="header-tool" id="messages">${icon('bell')}<span>消息</span></button><button class="header-tool" id="help">${icon('help')}<span>帮助</span></button><button class="r-user" id="user-menu"><span class="r-avatar">王</span><span><strong>${state.viewer.name}</strong><small>${state.viewer.role}</small></span></button></div><div class="r-tabs"><button class="active">教研空间</button><button id="following-tab">我的关注</button></div></header>`}
function researchPath(){return `<section class="research-path r-panel"><div class="panel-head"><h2>教研路径</h2><button id="all-topics">查看全部课题　›</button></div><div class="path-steps">${state.stages.map((s,i)=>`<button class="r-step ${state.activeStage===i+1?'current':''}" data-stage="${i+1}" style="--step-color:${i<2?'#d71e1e':i===2?'#ee6c21':i===3?'#ae8c1b':i===4?'#397d42':'#bbb'}"><strong>${s[0]}</strong><small>${s[1]}</small><i>${i+1}</i></button>`).join('')}</div><div class="path-counts">${state.counts.map(([l,n],i)=>`<button class="${state.selectedStatus===i?'active':''}" data-status="${i}">${l}　 ${n}</button>`).join('')}</div></section>`}
const tabNames=[['versions','课程版本'],['assessments','测评内容'],['resources','资源库'],['feedback','教师反馈'],['reviews','评审任务'],['insights','数据洞察'],['mind','MindMate 工具']];
function association(){return `<section class="association r-panel"><div class="assoc-tabs">${tabNames.map(([id,l])=>`<button data-assoc="${id}" class="${state.activeTab===id?'active':''}">${l}</button>`).join('')}<button class="all-link" id="assoc-all">查看全部版本　›</button></div>${associationBody()}</section>`}
function associationBody(){if(state.activeTab!=='versions')return `<div style="height:190px;display:grid;place-items:center;text-align:center;color:#69706b"><div><strong style="font-size:16px">${tabNames.find(x=>x[0]===state.activeTab)?.[1]}</strong><p>当前关联对象已从统一状态读取，点击右侧任务或反馈可继续追踪。</p><button class="r-btn" id="assoc-return">返回课程版本</button></div></div>`;return `<div class="table-caption">关联版本（${state.versions.length}）</div><table class="version-table"><thead><tr><th>版本名称</th><th>版本号</th><th>状态</th><th>关联课题阶段</th><th>更新者</th><th>更新时间</th><th>操作</th></tr></thead><tbody>${state.versions.map((v,i)=>`<tr><td>${v.name}</td><td>${v.version}</td><td><span class="pill ${v.status==='待评审'?'review':v.status==='已归档'?'archive':v.status==='试用中'?'trial':''}">${v.status}</span></td><td>${v.stage}</td><td>${v.editor}</td><td>${v.updated}</td><td><button data-version="${i}">查看</button></td></tr>`).join('')}</tbody></table>`}
function resources(){const colors=['#2474c4','#438d2e','#df8c19','#d12128','#9850d2','#287dc8'];return `<section class="resource-panel r-panel"><div class="panel-head"><h3>资源库 <small>（与课题关联）</small></h3><button id="resource-all">进入资源库　›</button></div><div class="resource-grid">${state.resources.map((r,i)=>`<button class="resource-item" data-resource="${i}" style="color:${colors[i]}">${icon(r[3])}<span style="color:#333"><strong>${r[0]}</strong><b>${r[1]}</b><small>较上周 <em>+${r[2]}</em></small></span></button>`).join('')}</div></section>`}
function spark(values){const pts=values.map((v,i)=>[i*(116/(values.length-1)),43-v*.35]);const d=pts.map((p,i)=>(i?'L':'M')+p.join(' ')).join(' ');return `<svg class="spark" viewBox="0 0 116 45" preserveAspectRatio="none"><path d="${d}"/>${pts.map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="1.5"/>`).join('')}</svg>`}
function insights(){return `<section class="insights r-panel"><div class="panel-head"><h3>数据洞察 <small>（近 30 天）</small></h3></div><div class="insight-grid"><article class="insight-card"><h4>课程使用覆盖率</h4>${state.ui.dataInsufficient?'<div class="no-data"><div><strong>数据不足</strong><p>暂无可用数据</p></div></div>':'<div class="metric-copy"><b>74%</b><small>覆盖 18 所学校</small></div>'}</article><article class="insight-card"><h4>测评参与率</h4><div class="metric-row"><div class="ring" style="--value:68"><span>68%</span></div><div class="metric-copy"><b>68%</b><small>较上周 <span style="color:#37804a">+12%</span></small><small>参与 1,248 人</small></div></div></article><article class="insight-card"><h4>学生朗读能力提升</h4><div class="metric-row"><div class="ring" style="--value:62"><span>62%</span></div><div class="metric-copy"><b>62%</b><small>较上周 <span style="color:#37804a">+8%</span></small><small>平均提升 12.6 分</small></div></div></article><article class="insight-card"><h4>资源使用次数</h4><div class="metric-copy"><b>2,846<small> 次</small></b><small>较上周 <span style="color:#37804a">+18%</span></small></div>${spark([15,18,14,20,19,28,33,46,50])}</article><article class="insight-card"><h4>反馈采纳率</h4><div class="metric-copy"><b>54%</b><small>较上周 <span style="color:#37804a">+9%</span></small></div>${spark([23,17,14,22,21,31,30,39,47])}</article></div></section>`}
function activeTopic(){if(state.ui.noActiveTopic)return `<section class="active-topic r-panel"><div class="panel-head"><h2>当前活跃课题</h2></div><div style="display:grid;place-items:center;height:160px;text-align:center;color:#727873"><div><strong>暂无活跃课题</strong><p>可以从教师反馈或数据洞察发起新的课题。</p><button class="r-btn primary" id="create-topic">创建课题</button></div></div></section>`;const t=state.topic;return `<section class="active-topic r-panel"><div class="panel-head"><h2>当前活跃课题</h2><button>已选 1 个课题</button></div><div class="topic-title"><h2>${t.title}</h2><span class="topic-status">${t.status}</span></div><div class="topic-meta"><div><span>课题编号</span><strong>${t.id}</strong></div><div><span>学段学科</span><strong>${t.grade}</strong></div><div><span>负责人</span><strong>${t.owner}</strong></div><div><span>创建时间</span><strong>${t.created}</strong></div><div><span>阶段</span><strong>${t.stage}</strong></div><div><span>参与人</span><strong>${t.members} 人</strong></div></div><div class="topic-progress"><div><span>课题进度</span><strong>${t.progress}%</strong></div><span class="progress-track"><i style="width:${t.progress}%"></i></span></div><button class="outline-red" id="topic-detail">进入课题详情</button></section>`}
function pending(){const data=[['待评审任务',state.counts[1][1]],['教师反馈',12],['试用反馈',8],['待发布版本',state.counts[3][1]]];return `<section class="pending-panel r-panel"><div class="panel-head"><h3>待处理事项</h3></div><div class="pending-grid">${data.map((d,i)=>`<button class="pending-item" data-pending="${i}"><strong>${d[0]}</strong><b>${d[1]}</b></button>`).join('')}</div></section>`}
function feedback(){return `<section class="feedback-panel r-panel"><div class="panel-head"><h3>教师反馈 <small>（近 7 天）</small></h3><button id="feedback-all">查看全部　›</button></div><div class="feedback-list">${state.feedback.map((f,i)=>`<button class="feedback-item" data-feedback="${i}"><span class="feedback-avatar">${f.teacher[0]}</span><span><strong>${f.teacher}<em class="feedback-tag ${i===1?'orange':''}">${f.tag}</em></strong><p>${f.text}</p><small>来自：${f.source}</small></span><time>${f.time}</time></button>`).join('')}</div></section>`}
function mindTools(){return `<section class="mind-panel r-panel"><div class="panel-head"><h3>MindMate 工具箱</h3><button id="mind-more">了解更多　›</button></div><div class="mind-list"><article class="mind-item"><span class="mind-icon">${icon('brain')}</span><span><strong>MindMate 智能助手</strong><small>教研问答、方案生成、文献检索</small></span><button data-tool="MindMate">进入</button></article><article class="mind-item"><span class="mind-icon">${icon('graph')}</span><span><strong>MindGraph 思维导图</strong><small>可视化梳理问题与方案结构</small></span><button data-tool="MindGraph">进入</button></article></div></section>`}
function bind(){document.querySelectorAll('[data-route]').forEach(x=>x.onclick=e=>{e.preventDefault();route(x.dataset.route)});document.querySelectorAll('[data-stage]').forEach(x=>x.onclick=()=>{state.activeStage=+x.dataset.stage;render();toast(`教研路径已定位到“${state.stages[state.activeStage-1][0]}”。`)});document.querySelectorAll('[data-status]').forEach(x=>x.onclick=()=>{state.selectedStatus=+x.dataset.status;render();toast(`已筛选${state.counts[state.selectedStatus][0]}课题。`)});document.querySelectorAll('[data-assoc]').forEach(x=>x.onclick=()=>{state.activeTab=x.dataset.assoc;render()});document.querySelector('#assoc-return')?.addEventListener('click',()=>{state.activeTab='versions';render()});document.querySelectorAll('[data-version]').forEach(x=>x.onclick=()=>versionDetail(+x.dataset.version));document.querySelectorAll('[data-resource]').forEach(x=>x.onclick=()=>resourceDetail(+x.dataset.resource));document.querySelectorAll('[data-pending]').forEach(x=>x.onclick=()=>pendingDetail(+x.dataset.pending));document.querySelectorAll('[data-feedback]').forEach(x=>x.onclick=()=>traceFeedback(+x.dataset.feedback));document.querySelectorAll('[data-tool]').forEach(x=>x.onclick=()=>openTool(x.dataset.tool));document.querySelector('#topic-detail')?.addEventListener('click',topicDetail);document.querySelector('#create-topic')?.addEventListener('click',createTopic);document.querySelector('#global-search')?.addEventListener('keydown',e=>{if(e.key==='Enter')search(e.target.value)});document.querySelector('#all-topics')?.addEventListener('click',()=>openModal('全部教研课题','课题列表页面已进入后续逐页开发队列。当前可通过路径状态继续筛选。'));document.querySelector('#resource-all')?.addEventListener('click',()=>route('/resources'));document.querySelector('#feedback-all')?.addEventListener('click',()=>{state.activeTab='feedback';render()});document.querySelector('#following-tab')?.addEventListener('click',()=>openModal('我的关注','关注课题、课程版本和教师反馈将在此汇总。'));document.querySelector('#messages')?.addEventListener('click',()=>openModal('消息','当前有 3 条评审提醒和 2 条教师反馈更新。'));document.querySelector('#help')?.addEventListener('click',()=>openModal('教研中心帮助','沿着问题、证据、方案、试用、评审和发布路径推进课题；所有发布仍需真实权限和后端确认。'));document.querySelector('#user-menu')?.addEventListener('click',demoStates);document.querySelector('#brand-story')?.addEventListener('click',()=>openModal('援藏教育','以真实课堂问题为起点，让每一次教学改进都有证据、版本与反馈。'));document.querySelector('#mind-more')?.addEventListener('click',()=>{state.activeTab='mind';render()});document.querySelector('#research-retry')?.addEventListener('click',retry)}
function route(path){if(path==='/research'){if(location.origin!=='null')history.pushState({},'',path+(qaMode?'?qa=1':''));render();return}toast('该教研页面已进入后续逐页还原队列。')}
function versionDetail(i){const v=state.versions[i];openModal(`${v.version} 版本详情`,`<strong>${v.name}</strong><p>状态：${v.status}</p><p>关联阶段：${v.stage}</p><p>更新者：${v.editor}　更新时间：${v.updated}</p><p>版本内容、差异和发布记录应由真实版本接口返回。</p>`)}
function resourceDetail(i){const r=state.resources[i];openModal(`${r[0]}资源`,`当前关联 ${r[1]} 项，较上周新增 ${r[2]} 项。资源详情、版权和可见范围由后端权限过滤。`)}
function pendingDetail(i){const tabs=['reviews','feedback','assessments','versions'];state.activeTab=tabs[i];render();toast('已定位到对应待处理对象。')}
function traceFeedback(i){const f=state.feedback[i];const v=state.versions.find(x=>x.version===f.version);openModal('反馈证据链',`<strong>${f.teacher} · ${f.tag}</strong><p>${f.text}</p><p>来源：${f.source}</p><hr><p>关联课程版本：${v?.version||'待关联'} · ${v?.name||''}</p><p>建议动作：建立修改任务并进入评审，不能以 AI 文本直接替代教研结论。</p><button class="r-btn primary" id="create-change-task">创建修改任务</button>`);setTimeout(()=>document.querySelector('#create-change-task')?.addEventListener('click',()=>{closeModal();state.counts[0][1]++;toast('修改任务已创建并关联教师反馈。','success')}),0)}
function topicDetail(){openModal(state.topic.title,`课题 ${state.topic.id} 当前位于 ${state.topic.stage}，进度 ${state.topic.progress}%。进入详情后可查看问题、证据、方案、试用记录和评审意见。`)}
function createTopic(){openForm('创建教研课题',`<label style="display:block;margin-bottom:12px">课题名称<input id="new-topic-title" style="width:100%;height:38px;margin-top:5px;border:1px solid #ddd;border-radius:5px;padding:0 10px"></label><label style="display:block">问题来源<select id="new-topic-source" style="width:100%;height:38px;margin-top:5px;border:1px solid #ddd;border-radius:5px"><option>教师反馈</option><option>测评数据</option><option>课程试用</option></select></label>`,()=>{const title=document.querySelector('#new-topic-title').value.trim();if(!title)return toast('请输入课题名称。','error');state.topic={...defaults.topic,title,status:'进行中',progress:0};state.ui.noActiveTopic=false;closeModal();render();toast('课题草稿已创建，等待补充证据。','success')})}
function openTool(name){openModal(`进入 ${name}`,`${name} 只提供教研辅助。打开前将共享当前课题标题和已授权资料范围；生成内容需要人工核验，不能直接发布为课程或测评结论。`)}
function search(q){state.ui.search=q.trim();if(!state.ui.search)return toast('请输入搜索关键词。','error');const match=state.versions.filter(v=>v.name.includes(state.ui.search)||v.version.includes(state.ui.search)).length+state.feedback.filter(f=>f.text.includes(state.ui.search)).length;toast(`找到 ${match} 条与“${state.ui.search}”相关的内容。`,'success')}
function demoStates(){openForm('教研中心状态演示',`<select id="research-state" style="width:100%;height:40px;border:1px solid #ddd;border-radius:5px"><option value="normal">正常状态</option><option value="none">无活跃课题</option><option value="backlog">待评审堆积</option><option value="insufficient">数据不足</option><option value="error">服务错误</option></select>`,()=>{const v=document.querySelector('#research-state').value;state.ui.noActiveTopic=v==='none';state.ui.reviewBacklog=v==='backlog';state.ui.dataInsufficient=v==='insufficient';if(v==='backlog')state.counts[1][1]=23;if(v==='normal'){state.ui.noActiveTopic=false;state.ui.dataInsufficient=false;state.counts[1][1]=5}if(v==='error')state.ui.pageState='error';closeModal();render();toast('教研中心状态已切换。','success')})}
function retry(){state.ui.pageState='loading';render();try{location.reload()}catch(_){state.ui.pageState='error';render();toast('刷新失败，请手动按 F5 重载页面。','error')}}
function pageState(title,text,loading){app.innerHTML=`<div class="r-shell">${sidebar()}${header()}<main class="page-state"><div><h2>${title}</h2><p>${text}</p>${loading?'':'<button class="r-btn primary" id="research-retry">重新加载</button>'}</div></main></div>`;bind()}
function openModal(title,body){state.ui.modal={title,body,type:'info'};renderModal()}function openForm(title,body,onConfirm){state.ui.modal={title,body,type:'form',onConfirm};renderModal()}
function renderModal(){const m=state.ui.modal;if(!m){modalRoot.innerHTML='';return}modalRoot.innerHTML=`<div class="r-modal-backdrop"><section class="r-modal" role="dialog" aria-modal="true"><div class="r-modal-head"><strong>${m.title}</strong><button id="r-modal-close" aria-label="关闭">×</button></div><div class="r-modal-body">${m.body}</div><div class="r-modal-actions"><button class="r-btn" id="r-modal-cancel">取消</button><button class="r-btn primary" id="r-modal-confirm">${m.type==='form'?'保存':'知道了'}</button></div></section></div>`;document.querySelector('#r-modal-close').onclick=closeModal;document.querySelector('#r-modal-cancel').onclick=closeModal;document.querySelector('#r-modal-confirm').onclick=m.type==='form'?m.onConfirm:closeModal;document.querySelector('.r-modal-backdrop').onclick=e=>{if(e.target===e.currentTarget)closeModal()}}
function closeModal(){state.ui.modal=null;renderModal()}function toast(t,type=''){const e=document.createElement('div');e.className=`research-toast ${type}`;e.textContent=t;toastRoot.append(e);setTimeout(()=>e.remove(),qaMode?700:2800)}function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('#global-search')?.focus()}if(e.key==='Escape')closeModal()});window.addEventListener('popstate',render);
window.YuzanResearch={hydrate(n){state=merge(state,n);render()},getState(){return clone(state)},async loadBackendState(url){state.ui.pageState='loading';render();try{const r=await fetch(url);if(!r.ok)throw Error('HTTP '+r.status);state=merge(state,await r.json());state.ui.pageState='normal';render()}catch(e){state.ui.pageState='error';render();throw e}},setDemoState(name){if(name==='no-topic')state.ui.noActiveTopic=true;if(name==='backlog'){state.ui.reviewBacklog=true;state.counts[1][1]=23}if(name==='insufficient')state.ui.dataInsufficient=true;if(name==='error')state.ui.pageState='error';render()}};
render();
})();
