import type { TodayActivity } from "../types";

export const todayDemoActivities: TodayActivity[] = [
  {
    id: "read-plateau-morning",
    title: "读懂《高原的早晨》",
    reason: "先熟悉内容，朗读时会更从容。",
    durationMinutes: 12,
    completion: "读完全文，并回答 2 个理解问题。",
    help: "遇到生词时先看提示，也可以暂停后再回来。",
    type: "reading",
    state: "ready",
    priority: 100,
    teacherAdvice: "先慢读一遍，再找出描写声音的句子。",
  },
  {
    id: "write-morning-sentence",
    title: "补写一个清晨句子",
    reason: "把刚读到的词语用进自己的句子里。",
    durationMinutes: 8,
    completion: "写出一句完整的话并保存。",
    help: "可以先写看到什么，再补上听到什么。",
    type: "writing",
    state: "paused",
    priority: 80,
  },
  {
    id: "retest-greeting-rhythm",
    title: "问候语节奏复测",
    reason: "老师建议你再试一次句尾停顿。",
    durationMinutes: 6,
    completion: "完成逐句朗读；录音服务接入后才能提交。",
    help: "现在可以先看句子和节奏提示，不会产生假评分。",
    type: "retest",
    state: "retest-recommended",
    priority: 90,
    teacherAdvice: "不用着急，重点听清每句结尾。",
  },
  {
    id: "listen-rain-words",
    title: "回顾雨声词句",
    reason: "这是你今天已经完成的巩固练习。",
    durationMinutes: 5,
    completion: "已完成，只读回顾。",
    help: "需要时可以重新查看材料。",
    type: "listening",
    state: "completed",
    priority: 10,
  },
];
