import type { MembershipRole } from "../lib/api/types";

export type ProductPort =
  "STUDENT" | "TEACHER" | "VOLUNTEER" | "ADMIN" | "PUBLIC";
export type ProductFeatureStatus = "LIVE" | "TRUTHFUL_GAP" | "COMPATIBILITY";

export interface ProductRouteRegistration {
  id: string;
  path: string;
  label: string;
  roles: readonly MembershipRole[];
  port: ProductPort;
  parentId: string | null;
  entryForRole: readonly MembershipRole[];
  navigationVisible: boolean;
  deepLinkOnly: boolean;
  requiresSchool: boolean;
  requiresAuthentication?: boolean;
  developmentOnly?: boolean;
  featureStatus: ProductFeatureStatus;
  fallbackRoute: string;
}

export const PRODUCT_ROLES = [
  "STUDENT",
  "TEACHER",
  "VOLUNTEER",
  "SCHOOL_ADMIN",
  "PLATFORM_ADMIN",
  "RESEARCHER",
] as const satisfies readonly MembershipRole[];

const student = ["STUDENT"] as const;
const teacher = ["TEACHER"] as const;
const volunteer = ["VOLUNTEER"] as const;
const admin = ["SCHOOL_ADMIN", "PLATFORM_ADMIN"] as const;
const research = ["RESEARCHER", "SCHOOL_ADMIN", "PLATFORM_ADMIN"] as const;

export const productRouteRegistry = [
  route(
    "public-home",
    "/",
    "首页",
    PRODUCT_ROLES,
    "PUBLIC",
    null,
    [],
    true,
    false,
    false,
    "LIVE",
    "/",
  ),
  route(
    "public-login",
    "/login",
    "登录",
    PRODUCT_ROLES,
    "PUBLIC",
    "public-home",
    [],
    true,
    false,
    false,
    "LIVE",
    "/",
  ),
  route(
    "public-select-school",
    "/select-school",
    "切换学校",
    PRODUCT_ROLES,
    "PUBLIC",
    "public-home",
    [],
    false,
    false,
    false,
    "LIVE",
    "/login",
    { requiresAuthentication: true },
  ),
  route(
    "public-plans",
    "/plans",
    "套餐",
    PRODUCT_ROLES,
    "PUBLIC",
    "public-home",
    [],
    true,
    false,
    false,
    "LIVE",
    "/",
  ),
  route(
    "public-products-alias",
    "/products",
    "产品方案兼容入口",
    PRODUCT_ROLES,
    "PUBLIC",
    "public-plans",
    [],
    false,
    false,
    false,
    "COMPATIBILITY",
    "/plans",
  ),

  route(
    "student-today",
    "/student/today",
    "今日学习",
    student,
    "STUDENT",
    null,
    student,
    true,
    false,
    true,
    "LIVE",
    "/student/today",
  ),
  route(
    "student-courses",
    "/student/courses",
    "课程",
    student,
    "STUDENT",
    "student-today",
    [],
    true,
    false,
    true,
    "LIVE",
    "/student/today",
  ),
  route(
    "student-learning",
    "/student/learning/:activityId",
    "学习活动",
    student,
    "STUDENT",
    "student-today",
    [],
    false,
    true,
    true,
    "LIVE",
    "/student/today",
  ),
  route(
    "student-assessment",
    "/assessment",
    "测评",
    student,
    "STUDENT",
    "student-today",
    [],
    true,
    false,
    true,
    "TRUTHFUL_GAP",
    "/student/today",
  ),
  route(
    "student-assessment-reading",
    "/assessment/reading",
    "朗读测评",
    student,
    "STUDENT",
    "student-assessment",
    [],
    false,
    false,
    true,
    "TRUTHFUL_GAP",
    "/assessment",
  ),
  route(
    "student-assessment-written",
    "/assessment/written",
    "书面测评",
    student,
    "STUDENT",
    "student-assessment",
    [],
    false,
    false,
    true,
    "TRUTHFUL_GAP",
    "/assessment",
  ),
  route(
    "student-assessment-history",
    "/assessment/history",
    "测评历史",
    student,
    "STUDENT",
    "student-assessment",
    [],
    true,
    false,
    true,
    "TRUTHFUL_GAP",
    "/assessment",
  ),
  route(
    "student-assessment-report",
    "/assessment/report/:reportId",
    "测评报告",
    student,
    "STUDENT",
    "student-assessment-history",
    [],
    false,
    true,
    true,
    "TRUTHFUL_GAP",
    "/assessment/history",
  ),

  route(
    "teacher-home",
    "/teacher",
    "教师工作台",
    teacher,
    "TEACHER",
    null,
    teacher,
    true,
    false,
    true,
    "LIVE",
    "/teacher",
  ),
  route(
    "teacher-studio",
    "/studio",
    "课程工作室",
    teacher,
    "TEACHER",
    "teacher-home",
    [],
    true,
    false,
    true,
    "LIVE",
    "/teacher",
  ),
  route(
    "teacher-studio-draft",
    "/studio/:draftId",
    "课程草稿",
    teacher,
    "TEACHER",
    "teacher-studio",
    [],
    false,
    true,
    true,
    "LIVE",
    "/studio",
  ),
  route(
    "teacher-classes",
    "/teacher/classes",
    "班级",
    teacher,
    "TEACHER",
    "teacher-home",
    [],
    true,
    false,
    true,
    "LIVE",
    "/teacher",
  ),
  route(
    "teacher-class-detail",
    "/teacher/classes/:classId",
    "班级详情",
    teacher,
    "TEACHER",
    "teacher-classes",
    [],
    false,
    true,
    true,
    "LIVE",
    "/teacher/classes",
  ),
  route(
    "teacher-assignments",
    "/teacher/assignments",
    "作业",
    teacher,
    "TEACHER",
    "teacher-home",
    [],
    true,
    false,
    true,
    "LIVE",
    "/teacher",
  ),
  route(
    "teacher-assignment-new",
    "/teacher/assignments/new",
    "创建作业",
    teacher,
    "TEACHER",
    "teacher-assignments",
    [],
    false,
    false,
    true,
    "LIVE",
    "/teacher/assignments",
  ),
  route(
    "teacher-assignment-detail",
    "/teacher/assignments/:assignmentId",
    "作业详情",
    teacher,
    "TEACHER",
    "teacher-assignments",
    [],
    false,
    true,
    true,
    "LIVE",
    "/teacher/assignments",
  ),
  route(
    "teacher-review",
    "/teacher/review",
    "复核",
    teacher,
    "TEACHER",
    "teacher-home",
    [],
    true,
    false,
    true,
    "LIVE",
    "/teacher",
  ),
  route(
    "teacher-review-detail",
    "/teacher/review/:submissionId",
    "提交复核",
    teacher,
    "TEACHER",
    "teacher-review",
    [],
    false,
    true,
    true,
    "LIVE",
    "/teacher/review",
  ),
  route(
    "teacher-review-feedback",
    "/teacher/review/:submissionId/feedback",
    "提交反馈",
    teacher,
    "TEACHER",
    "teacher-review-detail",
    [],
    false,
    true,
    true,
    "LIVE",
    "/teacher/review",
  ),
  route(
    "teacher-assessments",
    "/teacher/assessments",
    "测评任务",
    teacher,
    "TEACHER",
    "teacher-home",
    [],
    true,
    false,
    true,
    "TRUTHFUL_GAP",
    "/teacher",
  ),
  route(
    "teacher-assessment-new",
    "/teacher/assessments/new",
    "创建测评",
    teacher,
    "TEACHER",
    "teacher-assessments",
    [],
    false,
    false,
    true,
    "TRUTHFUL_GAP",
    "/teacher/assessments",
  ),
  route(
    "teacher-assessment-detail",
    "/teacher/assessments/:taskId",
    "测评详情",
    teacher,
    "TEACHER",
    "teacher-assessments",
    [],
    false,
    true,
    true,
    "TRUTHFUL_GAP",
    "/teacher/assessments",
  ),
  route(
    "teacher-student-assessment-reports",
    "/teacher/students/:studentId/assessment-reports",
    "学生测评报告",
    teacher,
    "TEACHER",
    "teacher-assessments",
    [],
    false,
    true,
    true,
    "TRUTHFUL_GAP",
    "/teacher/assessments",
  ),
  route(
    "teacher-reports",
    "/reports",
    "报告",
    teacher,
    "TEACHER",
    "teacher-home",
    [],
    true,
    false,
    true,
    "LIVE",
    "/teacher",
  ),
  route(
    "teacher-report-detail",
    "/reports/:reportId",
    "报告详情",
    teacher,
    "TEACHER",
    "teacher-reports",
    [],
    false,
    true,
    true,
    "LIVE",
    "/reports",
  ),
  route(
    "teacher-student-report",
    "/reports/students/:studentId",
    "学生成长报告",
    teacher,
    "TEACHER",
    "teacher-reports",
    [],
    false,
    true,
    true,
    "LIVE",
    "/reports",
  ),
  route(
    "teacher-tools",
    "/teacher-tools",
    "教师工具",
    teacher,
    "TEACHER",
    "teacher-home",
    [],
    true,
    false,
    true,
    "LIVE",
    "/teacher",
  ),
  route(
    "teacher-tool-mindmate",
    "/teacher-tools/mindmate",
    "MindMate",
    teacher,
    "TEACHER",
    "teacher-tools",
    [],
    false,
    false,
    true,
    "TRUTHFUL_GAP",
    "/teacher-tools",
  ),
  route(
    "teacher-tool-mindgraph",
    "/teacher-tools/mindgraph",
    "MindGraph",
    teacher,
    "TEACHER",
    "teacher-tools",
    [],
    false,
    false,
    true,
    "TRUTHFUL_GAP",
    "/teacher-tools",
  ),
  route(
    "teacher-tool-translation",
    "/tools/tibetan-translation",
    "藏汉翻译",
    teacher,
    "TEACHER",
    "teacher-tools",
    [],
    false,
    false,
    true,
    "TRUTHFUL_GAP",
    "/teacher-tools",
  ),

  route(
    "volunteer-home",
    "/volunteer",
    "志愿者工作台",
    volunteer,
    "VOLUNTEER",
    null,
    volunteer,
    true,
    false,
    true,
    "LIVE",
    "/volunteer",
  ),
  route(
    "volunteer-training",
    "/training/volunteer",
    "培训中心",
    volunteer,
    "VOLUNTEER",
    "volunteer-home",
    [],
    true,
    false,
    true,
    "LIVE",
    "/volunteer",
  ),
  route(
    "volunteer-training-alias",
    "/training",
    "培训兼容入口",
    volunteer,
    "VOLUNTEER",
    "volunteer-training",
    [],
    false,
    false,
    true,
    "COMPATIBILITY",
    "/training/volunteer",
  ),

  route(
    "admin-home",
    "/admin",
    "平台管理",
    admin,
    "ADMIN",
    null,
    admin,
    true,
    false,
    true,
    "TRUTHFUL_GAP",
    "/admin",
  ),
  route(
    "research-home",
    "/research",
    "教研",
    research,
    "ADMIN",
    "admin-home",
    ["RESEARCHER"],
    true,
    false,
    true,
    "TRUTHFUL_GAP",
    "/admin",
  ),

  route(
    "development-icons",
    "/design/icons",
    "图标实验室",
    PRODUCT_ROLES,
    "PUBLIC",
    null,
    [],
    false,
    true,
    false,
    "TRUTHFUL_GAP",
    "/",
    { developmentOnly: true },
  ),
] as const satisfies readonly ProductRouteRegistration[];

function route(
  id: string,
  path: string,
  label: string,
  roles: readonly MembershipRole[],
  port: ProductPort,
  parentId: string | null,
  entryForRole: readonly MembershipRole[],
  navigationVisible: boolean,
  deepLinkOnly: boolean,
  requiresSchool: boolean,
  featureStatus: ProductFeatureStatus,
  fallbackRoute: string,
  extra: Partial<
    Pick<ProductRouteRegistration, "requiresAuthentication" | "developmentOnly">
  > = {},
): ProductRouteRegistration {
  return {
    id,
    path,
    label,
    roles,
    port,
    parentId,
    entryForRole,
    navigationVisible,
    deepLinkOnly,
    requiresSchool,
    featureStatus,
    fallbackRoute,
    ...extra,
  };
}

export function findProductRoute(
  path: string,
): ProductRouteRegistration | undefined {
  const pathname = path.split(/[?#]/, 1)[0] || "/";
  return productRouteRegistry.find((entry) =>
    routePatternMatches(entry.path, pathname),
  );
}

export function routePatternMatches(
  pattern: string,
  pathname: string,
): boolean {
  const patternParts = normalizedParts(pattern);
  const pathParts = normalizedParts(pathname);
  if (patternParts.length !== pathParts.length) return false;
  return patternParts.every(
    (part, index) => part.startsWith(":") || part === pathParts[index],
  );
}

function normalizedParts(path: string) {
  if (path === "/") return [];
  return path.replace(/^\/+|\/+$/g, "").split("/");
}

export function roleCanAccessRoute(
  role: MembershipRole,
  path: string,
): boolean {
  const entry = findProductRoute(path);
  return Boolean(
    entry &&
    !entry.developmentOnly &&
    (entry.roles as readonly MembershipRole[]).includes(role),
  );
}

export function defaultRouteForMembershipRole(role: MembershipRole): string {
  return (
    productRouteRegistry.find((entry) =>
      (entry.entryForRole as readonly MembershipRole[]).includes(role),
    )?.path ?? "/select-school"
  );
}

export function navigationRoutesForRole(
  role?: MembershipRole,
): ProductRouteRegistration[] {
  return productRouteRegistry.filter((entry) => {
    if (!entry.navigationVisible || entry.developmentOnly || entry.deepLinkOnly)
      return false;
    if (!role) return entry.port === "PUBLIC" && !entry.requiresAuthentication;
    return entry.port === "PUBLIC"
      ? entry.path !== "/login"
      : (entry.roles as readonly MembershipRole[]).includes(role);
  });
}
